/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * OpenCRVS is also distributed under the terms of the Civil Registration
 * & Healthcare Disclaimer located at http://opencrvs.org/license.
 *
 * Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
 */
import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  schema: [
    {
      'http://localhost:7070/graphql': {
        headers: { Authorization: `Bearer ${process.env.TOKEN}` }
      }
    }
  ],
  documents: ['src/**/*.ts*', '!src/utils/gateway.ts', '!src/**/*.test.ts*'],
  generates: {
    './src/utils/gateway.ts': {
      config: {
        scalars: {
          PlainDate: 'PlainDate'
        }
      },
      plugins: [
        'typescript',
        'typescript-operations',
        {
          add: {
            content: `/*
             * This Source Code Form is subject to the terms of the Mozilla Public
             * License, v. 2.0. If a copy of the MPL was not distributed with this
             * file, You can obtain one at https://mozilla.org/MPL/2.0/.
             *
             * OpenCRVS is also distributed under the terms of the Civil Registration
             * & Healthcare Disclaimer located at http://opencrvs.org/license.
             *
             * Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
             */

            /*
             * DO NOT EDIT! This file is auto-generated by yarn generate-gateway-types - see 'codegen.yml'
             */

            /* eslint-disable */
            import { PlainDate } from '@client/utils/date-formatting'

            `
          }
        }
      ]
    },
    './graphql.schema.json': {
      plugins: ['introspection']
    }
  },
  overwrite: true
}
export default config
