# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Disable previous access log configuration to avoid duplicate logging and ensure that only the new JSON format is used.
access_log off;

log_format json_combined escape=json
  '{'
    '"nginx.request_time":$request_time,'
    '"event.dataset":"nginx.access",'
    '"source.ip":"$remote_addr",'
    '"user.name":"$remote_user",'
    '"http.version":"$server_protocol",'
    '"http.response.status_code":$status,'
    '"http.response.body.bytes":$body_bytes_sent,'
    '"http.request.referrer":"$http_referer",'
    '"http.request.method":"$request_method",'
    '"user_agent.original":"$http_user_agent",'
    '"url.original":"$request_uri",'
    '"nginx.time":"$time_iso8601",'
    '"nginx.x_forwarded_for":"$http_x_forwarded_for"'
  '}';

access_log /var/log/nginx/access.log json_combined;
