# All OpenCRVS services will be available under domain:
hostname: opencrvs.localhost

# Access OpenCRVS services at http://opencrvs.localhost
# If SSL is enabled, You need to accept SSL Certificate on localhost for multiple endpoints:
# - login
# - register
# - countryconfig
# - config
# - client
# - ...
# That makes it easier to test the application locally without SSL
# On local environment SSL is disabled by default:
ingress:
  ssl_enabled: false

# On local environment services are exposed at NodePort as well and are available from Tilt
# To access service you need to click on the service name in Tilt UI:
service_type: NodePort

elasticsearch:
  auth_mode: auto

minio:
  auth_mode: auto
# Horizontal Pod Autoscaler (HPA) configuration:
# Disabled by default for local environment.
hpa:
  enabled: false

# Pod Disruption Budget (PDB) configuration:
# Disabled by default for local environment.
pdb:
  enabled: false

mongodb:
  auth_mode: auto

postgres:
  auth_mode: auto

redis:
  auth_mode: use_secret

image:
  tag: develop
