/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type ActionStatus = 'Accepted' | 'Rejected' | 'Requested'

export type ActionType =
  | 'APPROVE_CORRECTION'
  | 'ARCHIVE'
  | 'ASSIGN'
  | 'CREATE'
  | 'DECLARE'
  | 'DELETE'
  | 'DETECT_DUPLICATE'
  | 'MARKED_AS_DUPLICATE'
  | 'NOTIFY'
  | 'PRINT_CERTIFICATE'
  | 'READ'
  | 'REGISTER'
  | 'REJECT'
  | 'REJECT_CORRECTION'
  | 'REQUEST_CORRECTION'
  | 'UNASSIGN'
  | 'VALIDATE'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface EventActionDraft {
  actionType: string
  annotation: Generated<Json>
  createdAt: Generated<Timestamp>
  createdAtLocation: string
  createdBy: string
  createdByRole: string
  createdBySignature: string | null
  declaration: Generated<Json>
  eventId: string
  id: Generated<string>
  transactionId: string
}

export interface EventAction {
  actionType: ActionType
  annotation: Generated<Json>
  assignedTo: string | null
  createdAt: Generated<Timestamp>
  createdAtLocation: string | null
  createdBy: string
  createdByRole: string
  createdBySignature: string | null
  declaration: Generated<Json>
  eventId: string
  id: Generated<string>
  /**
   * References the original action if this is an asynchronous confirmation of it.
   */
  originalActionId: string | null
  reasonIsDuplicate: boolean | null
  reasonMessage: string | null
  registrationNumber: string | null
  status: ActionStatus
  transactionId: string
}

export interface Event {
  createdAt: Generated<Timestamp>
  eventType: string
  id: Generated<string>
  trackingId: string
  transactionId: string
  updatedAt: Generated<Timestamp>
}

export interface Location {
  externalId: string | null
  id: Generated<string>
  name: string
  parentId: string | null
}

export interface DB {
  eventActionDrafts: EventActionDraft
  eventActions: EventAction
  events: Event
  locations: Location
}
