-- Up Migration
CREATE EXTENSION IF NOT EXISTS mongo_fdw;

CREATE SERVER IF NOT EXISTS mongo FOREIGN DATA WRAPPER mongo_fdw ${MONGO_SERVER_OPTIONS};

CREATE USER MAPPING IF NOT EXISTS FOR USER SERVER mongo ${MONGO_USER_MAPPING_OPTIONS};

-- Down Migration
DROP USER MAPPING FOR USER SERVER mongo;

DROP SERVER mongo CASCADE;

DROP EXTENSION mongo_fdw CASCADE;
