exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("declarations")
    .del() // Deletes ALL existing entries
    .then(function() {
      // Inserts seed entries one by one in series
      return knex("declarations").insert({
        firstName: "Kojo",
        middleName: "Emmanuel",
        lastName: "Abraham",
        dob: "2017-06-25",
        personalIDNummber: "GH39047098",
        gender: "male",
        typeOfBirth: "single",
        placeOfDelivery: "Cape Coast Hospital",
        attendantAtBirth: "Midwife",
        hospitalName: "Cape Coast Hospital",
        streetNumber: "",
        addressLine1: "P.O. Box 23",
        addressLine2: "",
        town: "Cape Coast",
        district: "Cape Coast Metropolitan",
        region: "Central Region",
        zip: "",
        notes: "",

        mother_personalIDNummber: "GH37494872",
        mother_firstName: "Adzo",
        mother_middleName: "Enam",
        mother_maidenName: "Ayittey",
        mother_dob: "1985-02-02",
        mother_maritalStatus: "Married",
        mother_doMarriage: "2007-09-23",
        mother_durationOfMarriage: "10",
        mother_nationality: "Ghana",
        mother_mobileNumber: "024 222 3344",
        mother_emailAddress: "adzo.e.abraham@gmail.com",
        mother_streetNumber: "",
        mother_houseName: "",
        mother_addressLine1: "P.O. Box 5555",
        mother_addressLine2: "",
        mother_town: "Cape Coast",
        mother_district: "Cape Coast Metropolitan",
        mother_region: "Central Region",
        mother_zip: "",
        mother_childrenBornAlive: "3",
        mother_childrenBornLiving: "3",
        mother_foetalDeaths: "0",
        mother_dobLastPreviousBirth: "2005-12-23",
        mother_formalEducation: "University",
        mother_occupation: "Teacher",
        mother_religion: "Catholic",
        mother_gainfulEmployment: true,

        father_personalIDNummber: "GH37874872",
        father_firstName: "Kobena",
        father_middleName: "Dommie",
        father_lastName: "Abraham",
        father_dob: "1985-07-15",
        father_maritalStatus: "Married",
        father_doMarriage: "2007-09-23",
        father_durationOfMarriage: "10",
        father_nationality: "Ghana",
        father_mobileNumber: "024 222 3344",
        father_emailAddress: "kobena.d.abraham@gmail.com",
        father_streetNumber: "",
        father_houseName: "",
        father_addressLine1: "P.O. Box 5555",
        father_addressLine2: "",
        father_town: "Cape Coast",
        father_district: "Cape Coast Metropolitan",
        father_region: "Central Region",
        father_zip: "",
        father_formalEducation: "University",
        father_occupation: "Civil Servant",
        father_religion: "Catholic",
        father_gainfulEmployment: true,

        informant_personalIDNummber: "GH37874872",
        informant_firstName: "Ekuwa",
        informant_middleName: "Farhanah",
        informant_lastName: "Ayittey",
        informant_relationship: "Mother's mother",
        informant_mobileNumber: "",
        informant_emailAddress: "",
        informant_streetNumber: "",
        informant_houseName: "",
        informant_addressLine1: "P.O. Box 5555",
        informant_addressLine2: "",
        informant_town: "Cape Coast",
        informant_district: "Cape Coast Metropolitan",
        informant_region: "Central Region",
        informant_zip: ""
      });
    })
    .then(function() {
      return knex("declarations").insert({
        firstName: "Kwasi",
        middleName: "Kwarfo",
        lastName: "Adarkwa",
        dob: "2017-06-25",
        personalIDNummber: "GH39049432",
        gender: "male",
        typeOfBirth: "single",
        placeOfDelivery: "Abura Clinic",
        attendantAtBirth: "Midwife",
        hospitalName: "Abura Clinic",
        streetNumber: "",
        addressLine1: "P.O. Box 19",
        addressLine2: "",
        town: "Abura",
        district: "Abura/Asebu/Kwamankese",
        region: "Central Region",
        zip: "",
        notes: "",

        mother_personalIDNummber: "GH37494872",
        mother_firstName: "Jane",
        mother_middleName: "Naana",
        mother_maidenName: "Adarkwa",
        mother_dob: "1982-12-02",
        mother_maritalStatus: "Married",
        mother_doMarriage: "2006-06-15",
        mother_durationOfMarriage: "11",
        mother_nationality: "Ghana",
        mother_mobileNumber: "024 239 6756",
        mother_emailAddress: "jane.adarkwa@gmail.com",
        mother_streetNumber: "",
        mother_houseName: "",
        mother_addressLine1: "P.O. Box 78",
        mother_addressLine2: "",
        mother_town: "Abura",
        mother_district: "Abura/Asebu/Kwamankese",
        mother_region: "Central Region",
        mother_zip: "",
        mother_childrenBornAlive: "1",
        mother_childrenBornLiving: "1",
        mother_foetalDeaths: "0",
        mother_dobLastPreviousBirth: "",
        mother_formalEducation: "High School",
        mother_occupation: "",
        mother_religion: "Catholic",
        mother_gainfulEmployment: false,

        father_personalIDNummber: "GH37826031",
        father_firstName: "Kweku",
        father_middleName: "Joseph",
        father_lastName: "Adarkwa",
        father_dob: "1980-01-20",
        father_maritalStatus: "Married",
        father_doMarriage: "2006-06-15",
        father_durationOfMarriage: "11",
        father_nationality: "Ghana",
        father_mobileNumber: "024 239 5431",
        father_emailAddress: "kweku.j.adarkwa@gmail.com",
        father_streetNumber: "",
        father_houseName: "",
        father_addressLine1: "P.O. Box 78",
        father_addressLine2: "",
        father_town: "Abura",
        father_district: "Abura/Asebu/Kwamankese",
        father_region: "Central Region",
        father_zip: "",
        father_formalEducation: "University",
        father_occupation: "Doctor",
        father_religion: "Catholic",
        father_gainfulEmployment: true,

        informant_personalIDNummber: "GH30087872",
        informant_firstName: "George",
        informant_middleName: "Haytham",
        informant_lastName: "Grant",
        informant_relationship: "Mother's brother",
        informant_mobileNumber: "024 969 4585",
        informant_emailAddress: "george.grant@gmail.com",
        informant_streetNumber: "",
        informant_houseName: "",
        informant_addressLine1: "P.O. Box 21",
        informant_addressLine2: "",
        informant_town: "Abura",
        informant_district: "Abura/Asebu/Kwamankese",
        informant_region: "Central Region",
        informant_zip: ""
      });
    })
    .then(function() {
      return knex("declarations").insert({
        firstName: "Nana",
        middleName: "Oforiatta",
        lastName: "Ayim",
        dob: "2017-06-26",
        personalIDNummber: "GH39548326",
        gender: "female",
        typeOfBirth: "single",
        placeOfDelivery: "home",
        attendantAtBirth: "none",
        hospitalName: "",
        streetNumber: "",
        addressLine1: "P.O. Box 66",
        addressLine2: "",
        town: "Ekroful",
        district: "Gomoa East",
        region: "Central Region",
        zip: "",
        notes: "",

        mother_personalIDNummber: "GH37426832",
        mother_firstName: "Kisi",
        mother_middleName: "Huda",
        mother_maidenName: "Ayim",
        mother_dob: "1999-04-02",
        mother_maritalStatus: "Single",
        mother_doMarriage: "",
        mother_durationOfMarriage: "",
        mother_nationality: "Ghana",
        mother_mobileNumber: "024 221 3378",
        mother_emailAddress: "",
        mother_streetNumber: "",
        mother_houseName: "",
        mother_addressLine1: "P.O. Box 66",
        mother_addressLine2: "",
        mother_town: "Ekroful",
        mother_district: "Gomoa East",
        mother_region: "Central Region",
        mother_zip: "",
        mother_childrenBornAlive: "1",
        mother_childrenBornLiving: "1",
        mother_foetalDeaths: "0",
        mother_dobLastPreviousBirth: "",
        mother_formalEducation: "High School",
        mother_occupation: "Textile Weaver",
        mother_religion: "",
        mother_gainfulEmployment: true,

        father_personalIDNummber: "GH37888795",
        father_firstName: "Donkor",
        father_middleName: "Fram",
        father_lastName: "Agyapong",
        father_dob: "1998-06-04",
        father_maritalStatus: "Single",
        father_doMarriage: "",
        father_durationOfMarriage: "",
        father_nationality: "Ghana",
        father_mobileNumber: "",
        father_emailAddress: "",
        father_streetNumber: "",
        father_houseName: "",
        father_addressLine1: "P.O. Box 58",
        father_addressLine2: "",
        father_town: "Ekroful",
        father_district: "Gomoa East",
        father_region: "Central Region",
        father_zip: "",
        father_formalEducation: "High School",
        father_occupation: "Market Trader",
        father_religion: "",
        father_gainfulEmployment: true,

        informant_personalIDNummber: "GH50025698",
        informant_firstName: "Lawrence",
        informant_middleName: "Emman",
        informant_lastName: "Kwegir Aggrey",
        informant_relationship: "Mother's father",
        informant_mobileNumber: "024 989 7845",
        informant_emailAddress: "",
        informant_streetNumber: "",
        informant_houseName: "",
        informant_addressLine1: "P.O. Box 66",
        informant_addressLine2: "",
        informant_town: "Ekroful",
        informant_district: "Gomoa East",
        informant_region: "Central Region",
        informant_zip: ""
      });
    });
};
