/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HapiRoutes {
  get: {
    '/locations/{locationId}/hierarchy': {
      request: {}
      response: {}
    }
  }
  post: {
    '/updateCertificate': {
      request: {
        id: string
        svgCode?: string
        svgFilename?: string
        svgDateUpdated?: number
        svgDateCreated?: number
        user?: string
        event?: string
        status?: string
      }
      response: {}
    }
  }
  put: {
    '/locations/{locationId}': {
      request: {
        name?: string
        alias?: string
        status?: 'active' | 'inactive'
        statistics?: {
          year: number
          male_population: number
          female_population: number
          population: number
          crude_birth_rate: number
        }
      }
      response: {}
    }
  }
  delete: {
    '/certificate/{certificateId}': {
      request: {}
      response: {}
    }
  }
}
