/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HapiRoutes {
  get: {
    '/ping': {
      request: {}
      response: {}
    }
  }
  post: {
    '/verifyUser': {
      request: {
        mobile?: string
        email?: string
      }
      response: {
        name?: {
          given: string[]
          use: string
          family: string
          [k: string]: unknown | undefined
        }[]
        mobile?: string
        email?: string
        scope?: string[]
        status?: string
        securityQuestionKey?: string
        id?: string
        username?: string
        practitionerId?: string
      }
    }
  }
  put?: {}
  delete: {
    '/searches': {
      request: {
        userId: string
        searchId: string
      }
      response: {}
    }
  }
}
