/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HapiRoutes {
  get: {
    '/ping': {
      request: never
      response: never
      params: never
    }
    '/webhooks': {
      request: never
      response: never
      params: never
    }
  }
  post: {
    '/deleteWebhooksByClientId': {
      request: never
      response: never
      params: never
    }
    '/webhooks': {
      request: {
        hub?: {
          callback?: string
          mode?: string
          topic?: string
          secret?: string
        }
      }
      response: never
      params: never
    }
    '/events/birth/mark-registered': {
      request: never
      response: never
      params: never
    }
    '/events/death/mark-registered': {
      request: never
      response: never
      params: never
    }
    '/events/marriage/mark-registered': {
      request: never
      response: never
      params: never
    }
  }
  put?: {}
  delete: {
    '/webhooks/{webhookId}': {
      request: never
      response: never
      params: {
        webhookId: string
      }
    }
  }
}
