/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * OpenCRVS is also distributed under the terms of the Civil Registration
 * & Healthcare Disclaimer located at http://opencrvs.org/license.
 *
 * Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
 */

export {
  Activity,
  Archive,
  ArchiveBox,
  ArchiveTray,
  ArrowCircleDown,
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowRight,
  Buildings,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartBar,
  ChartLine,
  ChatCircle,
  Check,
  CheckSquare,
  Circle,
  CircleWavyCheck,
  CircleWavyQuestion,
  Clock,
  Compass,
  Copy,
  Database,
  DeviceTabletCamera,
  DotsThreeVertical,
  Envelope,
  Export,
  Eye,
  EyeSlash,
  File,
  FileArrowUp,
  FileDotted,
  FileMinus,
  FilePlus,
  Files,
  FileSearch,
  FileText,
  FileX,
  Fingerprint,
  FloppyDisk,
  Gear,
  GitBranch,
  Globe,
  Handshake,
  IdentificationCard,
  List,
  ListBullets,
  Lock,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  MapPin,
  Medal,
  NotePencil,
  Paperclip,
  PaperPlaneTilt,
  Pen,
  Pencil,
  PencilCircle,
  PencilLine,
  PencilSimpleLine,
  Phone,
  Plus,
  Printer,
  QrCode,
  SignOut,
  Star,
  Sun,
  Target,
  TextT,
  Trash,
  UploadSimple,
  User,
  UserCircle,
  UserPlus,
  Users,
  WarningCircle,
  Webcam,
  X
} from 'phosphor-react'
export * from './custom-icons'
