-- Up Migration

GRANT USAGE ON SCHEMA app TO events_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA app
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO events_app;


-- Down Migration

ALTER DEFAULT PRIVILEGES IN SCHEMA app
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM events_app;

