-- Up Migration

ALTER TYPE action_type RENAME VALUE 'DETECT_DUPLICATE' TO 'DUPLICATE_DETECTED';

ALTER TYPE action_type RENAME VALUE 'MARKED_AS_DUPLICATE' TO 'MARK_NOT_DUPLICATE';

-- Down Migration

ALTER TYPE action_type RENAME VALUE 'DUPLICATE_DETECTED' TO 'DETECT_DUPLICATE';

ALTER TYPE action_type RENAME VALUE 'MARK_NOT_DUPLICATE' TO 'MARKED_AS_DUPLICATE';
