{{- if .Values.monitoring.enabled }}
{{- $elastic_host := default (printf "elasticsearch-0.elasticsearch.%s.svc.cluster.local" $.Release.Namespace) $.Values.elasticsearch.host }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      initContainers:
        - name: setup-indices
          image: appropriate/curl
          env:
            - name: ES_HOST
              value: {{ $elastic_host }}
            - name: ES_PORT
              value: "9200"
            - name: ES_USERNAME
              value: 'elastic'
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.admin_user_secret_name }}
                  key: ELASTIC_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for availability of Elasticsearch: http://${ES_HOST}:${ES_PORT}"
              ping_status_code=$(curl -s --connect-timeout 60 -u $ES_USERNAME:$ES_PASSWORD -o /dev/null -w '%{http_code}' "http://${ES_HOST}:${ES_PORT}")

              if [ "$ping_status_code" -ne 200 ]; then
                echo "Elasticsearch is not ready. API returned status code: $ping_status_code"
                exit 1
              fi

              echo 'Deleting Elastalert indices'
              indices='elastalert_status,elastalert_status_error,elastalert_status_past,elastalert_status_silence,elastalert_status_status'

              delete_status_code=$(curl -s --connect-timeout 60 -u $ES_USERNAME:$ES_PASSWORD -o /dev/null -w '%{http_code}' "http://${ES_HOST}:${ES_PORT}/${indices}?ignore_unavailable=true" -X DELETE)

              if [ "$delete_status_code" -ne 200 ]; then
                echo "Could not delete indices. API returned status code: $delete_status_code"
                exit 1
              fi
        - name: setup-rules
          image: "bash"
          env:
            - name: DOMAIN
              value: {{ .Values.hostname }}
          {{- include "render-env-vars" (dict "service_name" "elastalert" "Values" .Values) }}
          command: 
            - bash
            - -c
            - |
              apk add envsubst
              mkdir -p /rules
              for f in /rules-templates/*.yaml; do
                echo "processing file $f"
                envsubst < "$f" > "/rules/$(basename $f)"
              done
              [ ! -d /rules-custom ] && exit 0
              for f in /rules-custom/*.yaml; do
                echo "processing file $f"
                envsubst < "$f" > "/rules/$(basename $f)"
              done              
          volumeMounts:
            - name: rules
              mountPath: /rules
            - name: rules-templates
              mountPath: /rules-templates
          {{- if .Values.elastalert.custom_rules_configmap }}
            - name: custom-rules
              mountPath: /rules-custom
          {{- end }}
      containers:
        - name: elastalert
          image: jertel/elastalert2:2.25.0
          env:
            - name: DOMAIN
              value: {{ .Values.hostname }}
            - name: ES_HOST
              value: {{ $elastic_host }}
            - name: ES_PORT
              value: "9200"
            - name: ES_USERNAME
              value: 'elastic'
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.admin_user_secret_name }}
                  key: ELASTIC_PASSWORD
          {{- include "render-env-vars" (dict "service_name" "elastalert" "Values" .Values) }}
          volumeMounts:
            - name: config
              mountPath: /opt/elastalert/smtp.auth
              subPath: smtp.auth
            - name: config
              mountPath: /opt/elastalert/config.yaml
              subPath: elastalert.yaml
            - name:  rules
              mountPath: /opt/elastalert/rules
      volumes:
        - name: config
          configMap:
            name: elastalert-config
        - name: rules
          emptyDir: {}
        - name: rules-templates
          configMap:
            name: elastalert-rules
      {{- if .Values.elastalert.custom_rules_configmap }}
        - name: custom-rules
          configMap:
            name: {{ .Values.elastalert.custom_rules_configmap }}
      {{- end }}
{{- end }}