apiVersion: v1
data:
{{- range $path, $file := .Files.Glob "files/influxdb/*" }}
    {{ base $path }}: |
{{ toString $file | indent 8 }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    app: influxdb
  name: influxdb-scripts
