{{- if .Values.monitoring.enabled }}
{{- $encryption_secret_name := "kibana-encryption-secret" }}
{{- $encryption_secret := lookup "v1" "Secret" .Release.Namespace $encryption_secret_name }}
{{- if not $encryption_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $encryption_secret_name }}
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  KIBANA_ENCRYPTION_KEY: {{ .Values.encryptionKey | default (randAlphaNum 32) }}
{{- end }}

{{- $user_secret := lookup "v1" "Secret" .Release.Namespace .Values.kibana.users_secret }}
{{- if not $user_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kibana.users_secret }}
  annotations:
    "helm.sh/resource-policy": keep
stringData:
  KIBANA_USERNAME: {{ randAlphaNum 12 | lower }}
  KIBANA_PASSWORD: {{ randAlphaNum 32 }}
{{- end }}
{{- end }}
