{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.maxPayload: 10485760
    server.publicBaseUrl: "${PUBLIC_BASE_URL}"
    server.ssl.enabled: false
    server.defaultRoute: "/app/observability/overview"
    elasticsearch.hosts: [ "${KIBANA_SYSTEM_ELASTIC_URL}" ]
    elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    # Add any other static config you need from your configs
    monitoring.ui.container.elasticsearch.enabled: true
    xpack.encryptedSavedObjects.encryptionKey: "${KIBANA_ENCRYPTION_KEY}"
    xpack.reporting.encryptionKey: "${KIBANA_ENCRYPTION_KEY}"
    xpack.actions.preconfiguredAlertHistoryEsIndex: true
    logging.root.level: error
{{- end }}