apiVersion: v1
data:
{{- range $path, $file := .Files.Glob "files/mongo/*" }}
    {{ base $path }}: |
{{ toString $file | indent 8 }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    app: mongo
  name: mongodb-scripts
