apiVersion: v1
data:
    backup-functions.sh: |
{{ .Files.Get "files/common/backup-functions.sh" | indent 8 }}
{{- range $path, $file := .Files.Glob "files/mongo/*" }}
    {{ base $path }}: |
{{ toString $file | indent 8 }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    app: mongo
  name: mongodb-scripts
