{{ if .Values.postgres.enabled }}
{{- $storageType := default .Values.storage_type .Values.postgres.storage_type | default "pvc" }}

{{- if eq $storageType "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-data
spec:
  {{- if .Values.postgres.pvc.storage_class }}
  storageClassName: {{ .Values.postgres.pvc.storage_class | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.postgres.pvc.access_mode }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage_size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
    {{- if .Values.priority_class.enabled }}
      priorityClassName: {{ .Values.priority_class.name }}
    {{- end }}
    {{- $node_selector := default .Values.node_selector .Values.postgres.node_selector }}
    {{- if $node_selector }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
            {{- range $k, $v := $node_selector }}
              - key: {{ $k }}
                operator: In
                values:
                - {{ $v }}
            {{- end }}
    {{- end }}
      containers: 
        - name: postgres
          image: {{ .Values.postgres.image }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              /docker-entrypoint-initdb.d/postgres-backup-config.sh && \
              exec docker-entrypoint.sh postgres
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.admin_user_secret_name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.admin_user_secret_name }}
                  key: POSTGRES_PASSWORD
            - name: DB_TYPE
          {{- if and (eq .Values.postgres.backup.type "differential") (eq (include "postgres.backup_enabled" .) "true")}}
              value: backup
          {{- else if and (eq .Values.postgres.restore.type "differential") (eq (include "postgres.restore_enabled" .) "true")}}
              value: restore
          {{- else }}
              value: standalone
          {{- end }}
          {{- if (eq (include "postgres.use_pgBackRest" .) "true") }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.admin_user_secret_name }}
                  key: POSTGRES_USER
            - name: PGBACKREST_CONFIG
              value: /etc/pgbackrest/pgbackrest.conf
            - name: PGBACKREST_REPO1_PATH
          {{- if (eq (include "postgres.backup_enabled" .) "true") }}
              value: "{{ default .Values.postgres.backup.server_dir .Values.backup.backup_server_dir }}/postgres"
          {{- else }}
              value: "{{ default .Values.postgres.restore.server_dir .Values.restore.backup_server_dir }}/postgres"
          {{- end }}
            - name: PGBACKREST_REPO1_RETENTION_FULL
              value: "1"
            - name: PGBACKREST_REPO1_RETENTION_DIFF
              value: "7"
            - name: PGBACKREST_STANZA
              value: {{ .Values.postgres.backup.stanza }}
            - name: PGBACKREST_REPO1_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.postgres.backup.server_secret .Values.backup.backup_server_secret }}
                  key: user
            - name: PGBACKREST_REPO1_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.postgres.backup.server_secret .Values.backup.backup_server_secret }}
                  key: host
            - name: PGBACKREST_REPO1_TYPE
              value: posix
            - name: PGBACKREST_REPO1_CIPHER_TYPE
              value: aes-256-cbc
            - name: PGBACKREST_REPO1_CIPHER_PASS
              valueFrom:
                secretKeyRef:
                {{- if (eq (include "postgres.backup_enabled" .) "true") }}
                  name: {{ default .Values.postgres.backup.encryption_secret .Values.backup.backup_encryption_secret }}
                {{- else }}
                  name: {{ default .Values.postgres.restore.encryption_secret .Values.restore.backup_encryption_secret }}
                {{- end }}
                  key: backup_encryption_key
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "postgres" "Values" .Values) }}
          {{ include "resources-helper" (dict "service_name" "postgres" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
            - name: postgres-run
              mountPath: /run/postgresql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          {{- if (eq (include "postgres.use_pgBackRest" .) "true") }}
            - name: pgbackrest-config
              mountPath: /etc/pgbackrest
            - name: pgbackrest-ssh
              mountPath: /root/.ssh
              readOnly: true
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: init-script
          configMap:
            name: postgres-scripts
            defaultMode: 0755
            items:
              - key: postgres-backup-config.sh
                path: postgres-backup-config.sh
        - name: postgres-run
          emptyDir: {}
        - name: data
      {{- if eq $storageType "pvc" }}
          persistentVolumeClaim:
            claimName: postgres-data
      {{- else if eq $storageType "host_path" }}
          hostPath:
            path: {{ .Values.postgres.host_data_path | default "/data/postgres" }}
            type: DirectoryOrCreate
      {{- end }}
      {{- if (eq (include "postgres.use_pgBackRest" .) "true") }}
        - name: pgbackrest-config
          configMap:
            name: postgres-pgbackrest-config
        - name: pgbackrest-ssh
          secret:
          {{- if (eq (include "postgres.backup_enabled" .) "true") }}
            secretName: {{ default .Values.postgres.backup.server_secret .Values.backup.backup_server_secret }}
          {{- else }}
            secretName: {{ default .Values.postgres.restore.server_secret .Values.restore.backup_server_secret }}
          {{- end }}
            defaultMode: 0400
            items:
              - key: ssh_key
                path: id_rsa
      {{- end }}
{{- end }}
