coverage:
  status:
    patch:
      default:
        target: 80
    project:
      default: false
      auth:
        paths:
          - packages/auth
        threshold: 0.5
      gateway:
        paths:
          - packages/gateway
        threshold: 0.5
      login:
        paths:
          - packages/login
        threshold: 0.5
      notification:
        paths:
          - packages/notification
        threshold: 0.5
      register:
        paths:
          - packages/register
        threshold: 0.5
      performance:
        paths:
          - packages/performance
        threshold: 0.5
      user-mgnt:
        paths:
          - packages/user-mgnt
        threshold: 0.5
      commons:
        paths:
          - packages/commons
        threshold: 0.5
      workflow:
        paths:
          - packages/workflow
        threshold: 0.5
      search:
        paths:
          - packages/search
        threshold: 0.5
      metrics:
        paths:
          - packages/metrics
        threshold: 0.5

ignore:
  - 'packages/register/src/extract-translations.ts'
  - 'packages/register/src/index.tsx'
  - 'packages/register/src/registerServiceWorker.ts'
  - 'packages/register/src/src-sw.js'
  - 'packages/register/src/tests/graphql-schema-mock.ts'
  - 'packages/workflow/src/index.ts'
  - 'packages/gateway/src/index.ts'
  - 'packages/gateway/src/routes.ts'
  - 'packages/performance/src/index.tsx'
  - 'packages/performance/src/storage.ts'
  - 'packages/performance/src/components/ErrorBoundary.tsx'
  - 'packages/performance/src/components/TopMenu.tsx'
  - 'packages/performance/src/navigation/index.tsx'
