# You should always specify a full version here to ensure all of your developers
# are running the same version of Node.
FROM node:9.2.1
WORKDIR /usr/src/app

# Override the base log level (info).
ENV NPM_CONFIG_LOGLEVEL warn

# Default build env
ENV REACT_APP_API_GATEWAY_URL=http://localhost:7070/
ENV REACT_APP_LOCALE=gb
ENV REACT_APP_LANGUAGE=en

# Install and configure `serve`.
RUN yarn global add serve
CMD cd packages/register; serve -s build
EXPOSE 5000

# Copy all local files into the image (including all packages in the repo)
COPY . .

# Install all dependencies of the current project (for all local packages so that dependant packages are built and linked)
COPY package.json package.json
COPY yarn.lock yarn.lock
COPY lerna.json lerna.json
RUN yarn install

# Build for production.
RUN cd packages/register; yarn build --production
