FROM node:dubnium
WORKDIR /usr/src/app

# Override the base log level (info).
ENV NPM_CONFIG_LOGLEVEL warn

# Default build env
ENV REACT_APP_AUTH_API_URL=https://auth.opencrvs-staging.jembi.org/
ENV REACT_APP_REGISTER_APP_URL=https://register.opencrvs-staging.jembi.org/
ENV REACT_APP_PERFORMANCE_APP_URL=https://performance.opencrvs-staging.jembi.org/
ENV REACT_APP_COUNTRY=bgd
ENV REACT_APP_LANGUAGE=bn

# Install and configure `serve`.
RUN yarn global add serve
CMD serve -s build
EXPOSE 5000

# Copy all local files into the image (including all packages in the repo)
COPY . .

# Install all dependencies of the current project (for all packages so dependant packages are built and linked)
COPY package.json package.json
COPY yarn.lock yarn.lock
COPY lerna.json lerna.json
RUN yarn install

# Build for production.
RUN cd packages/login; yarn build --production

WORKDIR /usr/src/app/packages/login
