/* tslint:disable */
import { GraphQLResolveInfo, GraphQLScalarType } from 'graphql'
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface GQLQuery {
  listNotifications?: Array<GQLNotification | null>
  listBirthRegistrations?: Array<GQLBirthRegistration | null>
  listDeathRegistrations?: Array<GQLBirthRegistration | null>
}

export type GQLDate = any

export interface GQLNotification {
  id: string
  child?: GQLPerson
  mother?: GQLPerson
  father?: GQLPerson
  informant?: GQLPerson
  location?: GQLLocation
  createdAt?: GQLDate
  updatedAt?: GQLDate
}

export interface GQLPerson {
  id?: string
  identifier?: Array<GQLIdentityType | null>
  name?: Array<GQLHumanName | null>
  telecom?: Array<GQLContactPoint | null>
  gender?: string
  birthDate?: string
  maritalStatus?: GQLMaritalStatusType
  dateOfMarriage?: GQLDate
  multipleBirth?: number
  address?: Array<GQLAddress | null>
  photo?: Array<GQLAttachment | null>
  deceased?: boolean
  nationality?: Array<string | null>
  educationalAttainment?: GQLEducationType
}

export interface GQLIdentityType {
  id?: string
  type?: GQLIdentityIDType
}

export enum GQLIdentityIDType {
  PASSPORT = 'PASSPORT',
  NATIONAL_ID = 'NATIONAL_ID',
  DRIVING_LICENCE = 'DRIVING_LICENCE',
  BIRTH_REGISTRATION_NUMBER = 'BIRTH_REGISTRATION_NUMBER',
  DEATH_REGISTRATION_NUMBER = 'DEATH_REGISTRATION_NUMBER',
  REFUGEE_NUMBER = 'REFUGEE_NUMBER',
  ALIEN_NUMBER = 'ALIEN_NUMBER'
}

export interface GQLHumanName {
  use?: string
  firstNames?: string
  familyName?: string
}

export interface GQLContactPoint {
  system?: string
  value?: string
  use?: string
}

export enum GQLMaritalStatusType {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  WIDOWED = 'WIDOWED',
  DIVORCED = 'DIVORCED',
  NOT_STATED = 'NOT_STATED'
}

export interface GQLAddress {
  use?: string
  type?: GQLAddressType
  text?: string
  line?: Array<string | null>
  city?: string
  district?: string
  state?: string
  postalCode?: string
  country?: string
  from?: GQLDate
  to?: GQLDate
}

export enum GQLAddressType {
  CURRENT = 'CURRENT',
  PERMANENT = 'PERMANENT',
  MILITARY_BASE_OR_CANTONMENT = 'MILITARY_BASE_OR_CANTONMENT',
  IDP_CAMP = 'IDP_CAMP',
  UNHCR_CAMP = 'UNHCR_CAMP'
}

export interface GQLAttachment {
  id: string
  contentType?: string
  data?: string
  status?: string
  originalFileName?: string
  systemFileName?: string
  type?: GQLAttachmentType
  subject?: GQLAttachmentSubject
  createdAt?: GQLDate
}

export enum GQLAttachmentType {
  PASSPORT = 'PASSPORT',
  NATIONAL_ID = 'NATIONAL_ID',
  IMMUNISATION_CERTIFICATE = 'IMMUNISATION_CERTIFICATE',
  PAPER_FORM = 'PAPER_FORM',
  PASSPORT_PHOTO = 'PASSPORT_PHOTO',
  OTHER = 'OTHER'
}

export enum GQLAttachmentSubject {
  MOTHER = 'MOTHER',
  FATHER = 'FATHER',
  CHILD = 'CHILD',
  OTHER = 'OTHER'
}

export enum GQLEducationType {
  NO_SCHOOLING = 'NO_SCHOOLING',
  PRIMARY_ISCED_1 = 'PRIMARY_ISCED_1',
  LOWER_SECONDARY_ISCED_2 = 'LOWER_SECONDARY_ISCED_2',
  UPPER_SECONDARY_ISCED_3 = 'UPPER_SECONDARY_ISCED_3',
  POST_SECONDARY_ISCED_4 = 'POST_SECONDARY_ISCED_4',
  FIRST_STAGE_TERTIARY_ISCED_5 = 'FIRST_STAGE_TERTIARY_ISCED_5',
  SECOND_STAGE_TERTIARY_ISCED_6 = 'SECOND_STAGE_TERTIARY_ISCED_6',
  NOT_STATED = 'NOT_STATED'
}

export interface GQLLocation {
  id: string
  identifier?: Array<string | null>
  status?: string
  name?: string
  alias?: Array<string | null>
  description?: string
  type?: GQLLocationType
  telecom?: Array<GQLContactPoint | null>
  address?: GQLAddress
  longitude?: number
  latitude?: number
  altitude?: number
  geoData?: string
}

export enum GQLLocationType {
  HOSPITAL = 'HOSPITAL',
  OTHER_INSTITUTION = 'OTHER_INSTITUTION',
  PRIVATE_HOME = 'PRIVATE_HOME',
  OTHER = 'OTHER'
}

export interface GQLBirthRegistration {
  id: string
  registration?: GQLRegistration
  child?: GQLPerson
  mother?: GQLPerson
  father?: GQLPerson
  informant?: GQLPerson
  birthLocation?: GQLLocation
  birthType?: GQLBirthType
  weightAtBirth?: number
  attendantAtBirth?: GQLAttendantType
  birthRegistrationType?: GQLBirthRegType
  presentAtBirthRegistration?: GQLBirthRegPresence
  childrenBornAliveToMother?: number
  foetalDeathsToMother?: number
  lastPreviousLiveBirth?: GQLDate
  birthOrder?: number
  createdAt?: GQLDate
  updatedAt?: GQLDate
}

export interface GQLRegistration {
  trackingId?: string
  registrationNumber?: string
  paperFormID?: string
  page?: string
  book?: string
  contact?: GQLRegistrationContactType
  status?: Array<GQLRegWorkflow | null>
  type?: GQLRegistrationType
  attachments?: Array<GQLAttachment | null>
}

export enum GQLRegistrationContactType {
  MOTHER = 'MOTHER',
  FATHER = 'FATHER'
}

export interface GQLRegWorkflow {
  id: string
  type?: GQLRegStatus
  user?: GQLUser
  timestamp?: GQLDate
  comments?: Array<GQLComment | null>
  location?: GQLLocation
}

export enum GQLRegStatus {
  DECLARED = 'DECLARED',
  VERIFIED = 'VERIFIED',
  REGISTERED = 'REGISTERED',
  CERTIFIED = 'CERTIFIED'
}

export interface GQLUser {
  id: string
  userName?: string
  created?: GQLDate
  lastLoggedIn?: GQLDate
  firstName?: string
  lastName?: string
  telecom?: Array<GQLContactPoint | null>
  identifier?: Array<GQLIdentityType | null>
  role: Array<GQLUserRole | null>
  address?: GQLAddress
  primaryOffice?: GQLLocation
  currentLocation?: GQLLocation
  catchmentArea?: Array<GQLLocation | null>
}

export interface GQLUserRole {
  id: string
  type?: string
}

export interface GQLComment {
  id: string
  user?: GQLUser
  comment?: string
  createdAt?: GQLDate
}

export enum GQLRegistrationType {
  BIRTH = 'BIRTH',
  DEATH = 'DEATH'
}

export enum GQLBirthType {
  SINGLE = 'SINGLE',
  TWIN = 'TWIN',
  TRIPLET = 'TRIPLET',
  QUADRUPLET = 'QUADRUPLET',
  HIGHER_MULTIPLE_DELIVERY = 'HIGHER_MULTIPLE_DELIVERY'
}

export enum GQLAttendantType {
  PHYSICIAN = 'PHYSICIAN',
  NURSE = 'NURSE',
  NURSE_MIDWIFE = 'NURSE_MIDWIFE',
  MIDWIFE = 'MIDWIFE',
  OTHER_PARAMEDICAL_PERSONNEL = 'OTHER_PARAMEDICAL_PERSONNEL',
  LAYPERSON = 'LAYPERSON',
  NONE = 'NONE',
  OTHER = 'OTHER'
}

export enum GQLBirthRegType {
  BOTH_PARENTS = 'BOTH_PARENTS',
  SELF = 'SELF',
  INFORMANT_ONLY = 'INFORMANT_ONLY',
  MOTHER_ONLY = 'MOTHER_ONLY',
  FATHER_ONLY = 'FATHER_ONLY'
}

export enum GQLBirthRegPresence {
  BOTH_PARENTS = 'BOTH_PARENTS',
  INFORMANT_ONLY = 'INFORMANT_ONLY',
  MOTHER_ONLY = 'MOTHER_ONLY',
  FATHER_ONLY = 'FATHER_ONLY',
  OTHER = 'OTHER'
}

export interface GQLMutation {
  createNotification: GQLNotification
  voidNotification?: GQLNotification
  createBirthRegistration: string
  updateBirthRegistration: GQLBirthRegistration
  markBirthAsVerified?: GQLBirthRegistration
  markBirthAsRegistered?: GQLBirthRegistration
  markBirthAsCertified?: GQLBirthRegistration
  markBirthAsVoided?: GQLBirthRegistration
  createDeathRegistration: string
  updateDeathRegistration: GQLDeathRegistration
  markDeathAsVerified?: GQLDeathRegistration
  markDeathAsRegistered?: GQLDeathRegistration
  markDeathAsCertified?: GQLDeathRegistration
  markDeathAsVoided?: GQLDeathRegistration
}

export interface GQLNotificationInput {
  child?: GQLPersonInput
  mother?: GQLPersonInput
  father?: GQLPersonInput
  informant?: GQLPersonInput
  location?: GQLLocationInput
  createdAt?: GQLDate
  updatedAt?: GQLDate
}

export interface GQLPersonInput {
  identifier?: Array<GQLIdentityInput | null>
  name?: Array<GQLHumanNameInput | null>
  telecom?: Array<GQLContactPointInput | null>
  gender?: string
  birthDate?: string
  maritalStatus?: GQLMaritalStatusType
  dateOfMarriage?: GQLDate
  multipleBirth?: number
  address?: Array<GQLAddressInput | null>
  photo?: Array<GQLAttachmentInput | null>
  deceased?: boolean
  nationality?: Array<string | null>
  educationalAttainment?: GQLEducationType
}

export interface GQLIdentityInput {
  id?: string
  type?: GQLIdentityIDType
}

export interface GQLHumanNameInput {
  use?: string
  firstNames?: string
  familyName?: string
}

export interface GQLContactPointInput {
  system?: string
  value?: string
  use?: string
}

export interface GQLAddressInput {
  use?: string
  type?: GQLAddressType
  text?: string
  line?: Array<string | null>
  city?: string
  district?: string
  state?: string
  postalCode?: string
  country?: string
  from?: GQLDate
  to?: GQLDate
}

export interface GQLAttachmentInput {
  contentType?: string
  data?: string
  status?: string
  originalFileName?: string
  systemFileName?: string
  type?: GQLAttachmentType
  subject?: GQLAttachmentSubject
  createdAt?: GQLDate
}

export interface GQLLocationInput {
  identifier?: Array<string | null>
  status?: string
  name?: string
  alias?: Array<string | null>
  description?: string
  type?: GQLLocationType
  telecom?: Array<GQLContactPointInput | null>
  address?: GQLAddressInput
  longitude?: number
  latitude?: number
  altitude?: number
  geoData?: string
}

export interface GQLBirthRegistrationInput {
  registration?: GQLRegistrationInput
  child?: GQLPersonInput
  mother?: GQLPersonInput
  father?: GQLPersonInput
  informant?: GQLPersonInput
  birthLocation?: GQLLocationInput
  birthType?: GQLBirthType
  weightAtBirth?: number
  attendantAtBirth?: GQLAttendantType
  birthRegistrationType?: GQLBirthRegType
  presentAtBirthRegistration?: GQLBirthRegPresence
  childrenBornAliveToMother?: number
  foetalDeathsToMother?: number
  lastPreviousLiveBirth?: GQLDate
  birthOrder?: number
  createdAt?: GQLDate
  updatedAt?: GQLDate
}

export interface GQLRegistrationInput {
  trackingId?: string
  registrationNumber?: string
  paperFormID?: string
  page?: string
  book?: string
  contact?: GQLRegistrationContactType
  status?: Array<GQLRegWorkflowInput | null>
  type?: GQLRegistrationType
  attachments?: Array<GQLAttachmentInput | null>
  location?: GQLLocationInput
}

export interface GQLRegWorkflowInput {
  type?: GQLRegStatus
  user?: GQLUserInput
  timestamp?: GQLDate
  comments?: Array<GQLCommentInput | null>
  location?: GQLLocationInput
}

export interface GQLUserInput {
  userName?: string
  created?: GQLDate
  lastLoggedIn?: GQLDate
  firstName?: string
  lastName?: string
  telecom?: Array<GQLContactPointInput | null>
  identifier?: Array<GQLIdentityInput | null>
  role: Array<GQLUserRoleInput | null>
  address?: GQLAddressInput
  primaryOffice?: GQLLocationInput
  currentLocation?: GQLLocationInput
  catchmentArea?: Array<GQLLocationInput | null>
}

export interface GQLUserRoleInput {
  type?: string
}

export interface GQLCommentInput {
  user?: GQLUserInput
  comment?: string
  createdAt?: GQLDate
}

export interface GQLDeathRegistrationInput {
  registration?: GQLRegistrationInput
  deceased?: GQLPersonInput
  mother?: GQLPersonInput
  father?: GQLPersonInput
  informant?: GQLPersonInput
  spouse?: Array<GQLPersonInput | null>
  deathLocation?: GQLLocationInput
  causeOfDeath?: GQLCauseOfDeath
  createdAt?: GQLDate
  updatedAt?: GQLDate
}

export enum GQLCauseOfDeath {
  NATURAL = 'NATURAL',
  ACCIDENT = 'ACCIDENT',
  OTHER = 'OTHER'
}

export interface GQLDeathRegistration {
  id: string
  registration?: GQLRegistration
  deceased?: GQLPerson
  mother?: GQLPerson
  father?: GQLPerson
  informant?: GQLPerson
  spouse?: Array<GQLPerson | null>
  deathLocation?: GQLLocation
  causeOfDeath?: GQLCauseOfDeath
  createdAt?: GQLDate
  updatedAt?: GQLDate
}

export interface GQLDummy {
  dummy: string
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  Query?: GQLQueryTypeResolver
  Date?: GraphQLScalarType
  Notification?: GQLNotificationTypeResolver
  Person?: GQLPersonTypeResolver
  IdentityType?: GQLIdentityTypeTypeResolver
  HumanName?: GQLHumanNameTypeResolver
  ContactPoint?: GQLContactPointTypeResolver
  Address?: GQLAddressTypeResolver
  Attachment?: GQLAttachmentTypeResolver
  Location?: GQLLocationTypeResolver
  BirthRegistration?: GQLBirthRegistrationTypeResolver
  Registration?: GQLRegistrationTypeResolver
  RegWorkflow?: GQLRegWorkflowTypeResolver
  User?: GQLUserTypeResolver
  UserRole?: GQLUserRoleTypeResolver
  Comment?: GQLCommentTypeResolver
  Mutation?: GQLMutationTypeResolver
  DeathRegistration?: GQLDeathRegistrationTypeResolver
  Dummy?: GQLDummyTypeResolver
}
export interface GQLQueryTypeResolver<TParent = any> {
  listNotifications?: QueryToListNotificationsResolver<TParent>
  listBirthRegistrations?: QueryToListBirthRegistrationsResolver<TParent>
  listDeathRegistrations?: QueryToListDeathRegistrationsResolver<TParent>
}

export interface QueryToListNotificationsArgs {
  locationIds?: Array<string | null>
  status?: string
  userId?: string
  from?: GQLDate
  to?: GQLDate
}
export interface QueryToListNotificationsResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: QueryToListNotificationsArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface QueryToListBirthRegistrationsArgs {
  locationIds?: Array<string | null>
  status?: string
  userId?: string
  from?: GQLDate
  to?: GQLDate
}
export interface QueryToListBirthRegistrationsResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: QueryToListBirthRegistrationsArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface QueryToListDeathRegistrationsArgs {
  locationIds?: Array<string | null>
  status?: string
  userId?: string
  from?: GQLDate
  to?: GQLDate
}
export interface QueryToListDeathRegistrationsResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: QueryToListDeathRegistrationsArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLNotificationTypeResolver<TParent = any> {
  id?: NotificationToIdResolver<TParent>
  child?: NotificationToChildResolver<TParent>
  mother?: NotificationToMotherResolver<TParent>
  father?: NotificationToFatherResolver<TParent>
  informant?: NotificationToInformantResolver<TParent>
  location?: NotificationToLocationResolver<TParent>
  createdAt?: NotificationToCreatedAtResolver<TParent>
  updatedAt?: NotificationToUpdatedAtResolver<TParent>
}

export interface NotificationToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface NotificationToChildResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface NotificationToMotherResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface NotificationToFatherResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface NotificationToInformantResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface NotificationToLocationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface NotificationToCreatedAtResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface NotificationToUpdatedAtResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLPersonTypeResolver<TParent = any> {
  id?: PersonToIdResolver<TParent>
  identifier?: PersonToIdentifierResolver<TParent>
  name?: PersonToNameResolver<TParent>
  telecom?: PersonToTelecomResolver<TParent>
  gender?: PersonToGenderResolver<TParent>
  birthDate?: PersonToBirthDateResolver<TParent>
  maritalStatus?: PersonToMaritalStatusResolver<TParent>
  dateOfMarriage?: PersonToDateOfMarriageResolver<TParent>
  multipleBirth?: PersonToMultipleBirthResolver<TParent>
  address?: PersonToAddressResolver<TParent>
  photo?: PersonToPhotoResolver<TParent>
  deceased?: PersonToDeceasedResolver<TParent>
  nationality?: PersonToNationalityResolver<TParent>
  educationalAttainment?: PersonToEducationalAttainmentResolver<TParent>
}

export interface PersonToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToIdentifierResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToTelecomResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToGenderResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToBirthDateResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToMaritalStatusResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToDateOfMarriageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToMultipleBirthResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToAddressResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToPhotoResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToDeceasedResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToNationalityResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface PersonToEducationalAttainmentResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLIdentityTypeTypeResolver<TParent = any> {
  id?: IdentityTypeToIdResolver<TParent>
  type?: IdentityTypeToTypeResolver<TParent>
}

export interface IdentityTypeToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface IdentityTypeToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLHumanNameTypeResolver<TParent = any> {
  use?: HumanNameToUseResolver<TParent>
  firstNames?: HumanNameToFirstNamesResolver<TParent>
  familyName?: HumanNameToFamilyNameResolver<TParent>
}

export interface HumanNameToUseResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface HumanNameToFirstNamesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface HumanNameToFamilyNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLContactPointTypeResolver<TParent = any> {
  system?: ContactPointToSystemResolver<TParent>
  value?: ContactPointToValueResolver<TParent>
  use?: ContactPointToUseResolver<TParent>
}

export interface ContactPointToSystemResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface ContactPointToValueResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface ContactPointToUseResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLAddressTypeResolver<TParent = any> {
  use?: AddressToUseResolver<TParent>
  type?: AddressToTypeResolver<TParent>
  text?: AddressToTextResolver<TParent>
  line?: AddressToLineResolver<TParent>
  city?: AddressToCityResolver<TParent>
  district?: AddressToDistrictResolver<TParent>
  state?: AddressToStateResolver<TParent>
  postalCode?: AddressToPostalCodeResolver<TParent>
  country?: AddressToCountryResolver<TParent>
  from?: AddressToFromResolver<TParent>
  to?: AddressToToResolver<TParent>
}

export interface AddressToUseResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToTextResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToLineResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToCityResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToDistrictResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToStateResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToPostalCodeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToCountryResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToFromResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AddressToToResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLAttachmentTypeResolver<TParent = any> {
  id?: AttachmentToIdResolver<TParent>
  contentType?: AttachmentToContentTypeResolver<TParent>
  data?: AttachmentToDataResolver<TParent>
  status?: AttachmentToStatusResolver<TParent>
  originalFileName?: AttachmentToOriginalFileNameResolver<TParent>
  systemFileName?: AttachmentToSystemFileNameResolver<TParent>
  type?: AttachmentToTypeResolver<TParent>
  subject?: AttachmentToSubjectResolver<TParent>
  createdAt?: AttachmentToCreatedAtResolver<TParent>
}

export interface AttachmentToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToContentTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToDataResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToStatusResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToOriginalFileNameResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToSystemFileNameResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToSubjectResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface AttachmentToCreatedAtResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLLocationTypeResolver<TParent = any> {
  id?: LocationToIdResolver<TParent>
  identifier?: LocationToIdentifierResolver<TParent>
  status?: LocationToStatusResolver<TParent>
  name?: LocationToNameResolver<TParent>
  alias?: LocationToAliasResolver<TParent>
  description?: LocationToDescriptionResolver<TParent>
  type?: LocationToTypeResolver<TParent>
  telecom?: LocationToTelecomResolver<TParent>
  address?: LocationToAddressResolver<TParent>
  longitude?: LocationToLongitudeResolver<TParent>
  latitude?: LocationToLatitudeResolver<TParent>
  altitude?: LocationToAltitudeResolver<TParent>
  geoData?: LocationToGeoDataResolver<TParent>
}

export interface LocationToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToIdentifierResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToStatusResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToAliasResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToDescriptionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToTelecomResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToAddressResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToLongitudeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToLatitudeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToAltitudeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface LocationToGeoDataResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLBirthRegistrationTypeResolver<TParent = any> {
  id?: BirthRegistrationToIdResolver<TParent>
  registration?: BirthRegistrationToRegistrationResolver<TParent>
  child?: BirthRegistrationToChildResolver<TParent>
  mother?: BirthRegistrationToMotherResolver<TParent>
  father?: BirthRegistrationToFatherResolver<TParent>
  informant?: BirthRegistrationToInformantResolver<TParent>
  birthLocation?: BirthRegistrationToBirthLocationResolver<TParent>
  birthType?: BirthRegistrationToBirthTypeResolver<TParent>
  weightAtBirth?: BirthRegistrationToWeightAtBirthResolver<TParent>
  attendantAtBirth?: BirthRegistrationToAttendantAtBirthResolver<TParent>
  birthRegistrationType?: BirthRegistrationToBirthRegistrationTypeResolver<
    TParent
  >
  presentAtBirthRegistration?: BirthRegistrationToPresentAtBirthRegistrationResolver<
    TParent
  >
  childrenBornAliveToMother?: BirthRegistrationToChildrenBornAliveToMotherResolver<
    TParent
  >
  foetalDeathsToMother?: BirthRegistrationToFoetalDeathsToMotherResolver<
    TParent
  >
  lastPreviousLiveBirth?: BirthRegistrationToLastPreviousLiveBirthResolver<
    TParent
  >
  birthOrder?: BirthRegistrationToBirthOrderResolver<TParent>
  createdAt?: BirthRegistrationToCreatedAtResolver<TParent>
  updatedAt?: BirthRegistrationToUpdatedAtResolver<TParent>
}

export interface BirthRegistrationToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToRegistrationResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToChildResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToMotherResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToFatherResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToInformantResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToBirthLocationResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToBirthTypeResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToWeightAtBirthResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToAttendantAtBirthResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToBirthRegistrationTypeResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToPresentAtBirthRegistrationResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToChildrenBornAliveToMotherResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToFoetalDeathsToMotherResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToLastPreviousLiveBirthResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToBirthOrderResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToCreatedAtResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface BirthRegistrationToUpdatedAtResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLRegistrationTypeResolver<TParent = any> {
  trackingId?: RegistrationToTrackingIdResolver<TParent>
  registrationNumber?: RegistrationToRegistrationNumberResolver<TParent>
  paperFormID?: RegistrationToPaperFormIDResolver<TParent>
  page?: RegistrationToPageResolver<TParent>
  book?: RegistrationToBookResolver<TParent>
  contact?: RegistrationToContactResolver<TParent>
  status?: RegistrationToStatusResolver<TParent>
  type?: RegistrationToTypeResolver<TParent>
  attachments?: RegistrationToAttachmentsResolver<TParent>
}

export interface RegistrationToTrackingIdResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToRegistrationNumberResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToPaperFormIDResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToPageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToBookResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToContactResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToStatusResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegistrationToAttachmentsResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLRegWorkflowTypeResolver<TParent = any> {
  id?: RegWorkflowToIdResolver<TParent>
  type?: RegWorkflowToTypeResolver<TParent>
  user?: RegWorkflowToUserResolver<TParent>
  timestamp?: RegWorkflowToTimestampResolver<TParent>
  comments?: RegWorkflowToCommentsResolver<TParent>
  location?: RegWorkflowToLocationResolver<TParent>
}

export interface RegWorkflowToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegWorkflowToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegWorkflowToUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegWorkflowToTimestampResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegWorkflowToCommentsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface RegWorkflowToLocationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLUserTypeResolver<TParent = any> {
  id?: UserToIdResolver<TParent>
  userName?: UserToUserNameResolver<TParent>
  created?: UserToCreatedResolver<TParent>
  lastLoggedIn?: UserToLastLoggedInResolver<TParent>
  firstName?: UserToFirstNameResolver<TParent>
  lastName?: UserToLastNameResolver<TParent>
  telecom?: UserToTelecomResolver<TParent>
  identifier?: UserToIdentifierResolver<TParent>
  role?: UserToRoleResolver<TParent>
  address?: UserToAddressResolver<TParent>
  primaryOffice?: UserToPrimaryOfficeResolver<TParent>
  currentLocation?: UserToCurrentLocationResolver<TParent>
  catchmentArea?: UserToCatchmentAreaResolver<TParent>
}

export interface UserToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToUserNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToCreatedResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToLastLoggedInResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToFirstNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToLastNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToTelecomResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToIdentifierResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToRoleResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToAddressResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToPrimaryOfficeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToCurrentLocationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserToCatchmentAreaResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLUserRoleTypeResolver<TParent = any> {
  id?: UserRoleToIdResolver<TParent>
  type?: UserRoleToTypeResolver<TParent>
}

export interface UserRoleToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface UserRoleToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLCommentTypeResolver<TParent = any> {
  id?: CommentToIdResolver<TParent>
  user?: CommentToUserResolver<TParent>
  comment?: CommentToCommentResolver<TParent>
  createdAt?: CommentToCreatedAtResolver<TParent>
}

export interface CommentToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface CommentToUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface CommentToCommentResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface CommentToCreatedAtResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLMutationTypeResolver<TParent = any> {
  createNotification?: MutationToCreateNotificationResolver<TParent>
  voidNotification?: MutationToVoidNotificationResolver<TParent>
  createBirthRegistration?: MutationToCreateBirthRegistrationResolver<TParent>
  updateBirthRegistration?: MutationToUpdateBirthRegistrationResolver<TParent>
  markBirthAsVerified?: MutationToMarkBirthAsVerifiedResolver<TParent>
  markBirthAsRegistered?: MutationToMarkBirthAsRegisteredResolver<TParent>
  markBirthAsCertified?: MutationToMarkBirthAsCertifiedResolver<TParent>
  markBirthAsVoided?: MutationToMarkBirthAsVoidedResolver<TParent>
  createDeathRegistration?: MutationToCreateDeathRegistrationResolver<TParent>
  updateDeathRegistration?: MutationToUpdateDeathRegistrationResolver<TParent>
  markDeathAsVerified?: MutationToMarkDeathAsVerifiedResolver<TParent>
  markDeathAsRegistered?: MutationToMarkDeathAsRegisteredResolver<TParent>
  markDeathAsCertified?: MutationToMarkDeathAsCertifiedResolver<TParent>
  markDeathAsVoided?: MutationToMarkDeathAsVoidedResolver<TParent>
}

export interface MutationToCreateNotificationArgs {
  details: GQLNotificationInput
}
export interface MutationToCreateNotificationResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToCreateNotificationArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToVoidNotificationArgs {
  id: string
}
export interface MutationToVoidNotificationResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToVoidNotificationArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToCreateBirthRegistrationArgs {
  details: GQLBirthRegistrationInput
}
export interface MutationToCreateBirthRegistrationResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToCreateBirthRegistrationArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToUpdateBirthRegistrationArgs {
  id: string
  details: GQLBirthRegistrationInput
}
export interface MutationToUpdateBirthRegistrationResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToUpdateBirthRegistrationArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkBirthAsVerifiedArgs {
  id: string
  location?: GQLLocationInput
}
export interface MutationToMarkBirthAsVerifiedResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkBirthAsVerifiedArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkBirthAsRegisteredArgs {
  id: string
  location?: GQLLocationInput
}
export interface MutationToMarkBirthAsRegisteredResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkBirthAsRegisteredArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkBirthAsCertifiedArgs {
  id: string
  location?: GQLLocationInput
}
export interface MutationToMarkBirthAsCertifiedResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkBirthAsCertifiedArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkBirthAsVoidedArgs {
  id: string
  reason: string
  location?: GQLLocationInput
}
export interface MutationToMarkBirthAsVoidedResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkBirthAsVoidedArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToCreateDeathRegistrationArgs {
  details: GQLDeathRegistrationInput
}
export interface MutationToCreateDeathRegistrationResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToCreateDeathRegistrationArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToUpdateDeathRegistrationArgs {
  id: string
  details: GQLDeathRegistrationInput
}
export interface MutationToUpdateDeathRegistrationResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToUpdateDeathRegistrationArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkDeathAsVerifiedArgs {
  id: string
  location?: GQLLocationInput
}
export interface MutationToMarkDeathAsVerifiedResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkDeathAsVerifiedArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkDeathAsRegisteredArgs {
  id: string
  location?: GQLLocationInput
}
export interface MutationToMarkDeathAsRegisteredResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkDeathAsRegisteredArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkDeathAsCertifiedArgs {
  id: string
  location?: GQLLocationInput
}
export interface MutationToMarkDeathAsCertifiedResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkDeathAsCertifiedArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToMarkDeathAsVoidedArgs {
  id: string
  reason: string
  location?: GQLLocationInput
}
export interface MutationToMarkDeathAsVoidedResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToMarkDeathAsVoidedArgs,
    context: any,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLDeathRegistrationTypeResolver<TParent = any> {
  id?: DeathRegistrationToIdResolver<TParent>
  registration?: DeathRegistrationToRegistrationResolver<TParent>
  deceased?: DeathRegistrationToDeceasedResolver<TParent>
  mother?: DeathRegistrationToMotherResolver<TParent>
  father?: DeathRegistrationToFatherResolver<TParent>
  informant?: DeathRegistrationToInformantResolver<TParent>
  spouse?: DeathRegistrationToSpouseResolver<TParent>
  deathLocation?: DeathRegistrationToDeathLocationResolver<TParent>
  causeOfDeath?: DeathRegistrationToCauseOfDeathResolver<TParent>
  createdAt?: DeathRegistrationToCreatedAtResolver<TParent>
  updatedAt?: DeathRegistrationToUpdatedAtResolver<TParent>
}

export interface DeathRegistrationToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToRegistrationResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToDeceasedResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToMotherResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToFatherResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToInformantResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToSpouseResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToDeathLocationResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToCauseOfDeathResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToCreatedAtResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface DeathRegistrationToUpdatedAtResolver<
  TParent = any,
  TResult = any
> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}

export interface GQLDummyTypeResolver<TParent = any> {
  dummy?: DummyToDummyResolver<TParent>
}

export interface DummyToDummyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult
}
