import { Context } from './context'
/* tslint:disable */
 
import { GraphQLResolveInfo } from 'graphql'
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface GQLQuery {
  getUser?: GQLUser
  getUserByMobile?: GQLUser
  getUserByEmail?: GQLUser
  searchUsers?: GQLSearchUserResult
  verifyPasswordById?: GQLVerifyPasswordResult
}

export interface GQLMutation {
  createOrUpdateUser: GQLUser
  activateUser?: string
  changePassword?: string
  changePhone?: string
  changeEmail?: string
  changeAvatar?: GQLAvatar
  auditUser?: string
  resendInvite?: string
  usernameReminder?: string
  resetPasswordInvite?: string
}

export interface GQLDummy {
  dummy: string
}

export interface GQLUser {
  id: string
  name: Array<GQLHumanName>
  username?: string
  mobile?: string
  role: string
  email?: string
  fullHonorificName?: string
  status: GQLStatus
  primaryOfficeId: string
  signature?: GQLSignature
  avatar?: string
}

export interface GQLSearchUserResult {
  results?: Array<GQLUser | null>
  totalItems?: number
}

export interface GQLVerifyPasswordResult {
  mobile?: string
  scrope?: Array<string | null>
  status?: string
  username?: string
  id?: string
}

export interface GQLUserInput {
  id?: string
  name: Array<GQLHumanNameInput>
  identifier?: Array<GQLUserIdentifierInput | null>
  username?: string
  mobile?: string
  password?: string
  status?: GQLStatus
  role?: string
  email?: string
  fullHonorificName?: string
  primaryOfficeId?: string
  device?: string
  signature?: GQLSignatureInput
}

export interface GQLSecurityQuestionAnswer {
  questionKey?: string
  answer?: string
}

export interface GQLAvatar {
  type: string
  data: string
}

export interface GQLAvatarInput {
  type: string
  data: string
}

export interface GQLHumanName {
  use?: string
  firstNames?: string
  middleName?: string
  familyName?: string
  marriedLastName?: string
}

export const enum GQLStatus {
  active = 'active',
  deactivated = 'deactivated',
  pending = 'pending',
  disabled = 'disabled'
}

export interface GQLSignature {
  data?: string
  type?: string
}

export interface GQLHumanNameInput {
  use?: string
  firstNames?: string
  middleName?: string
  familyName?: string
  marriedLastName?: string
}

export interface GQLUserIdentifierInput {
  use?: string
  system?: string
  value?: string
}

export interface GQLSignatureInput {
  data: string
  type?: string
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  Query?: GQLQueryTypeResolver
  Mutation?: GQLMutationTypeResolver
  Dummy?: GQLDummyTypeResolver
  User?: GQLUserTypeResolver
  SearchUserResult?: GQLSearchUserResultTypeResolver
  VerifyPasswordResult?: GQLVerifyPasswordResultTypeResolver
  Avatar?: GQLAvatarTypeResolver
  HumanName?: GQLHumanNameTypeResolver
  Signature?: GQLSignatureTypeResolver
}
export interface GQLQueryTypeResolver<TParent = any> {
  getUser?: QueryToGetUserResolver<TParent>
  getUserByMobile?: QueryToGetUserByMobileResolver<TParent>
  getUserByEmail?: QueryToGetUserByEmailResolver<TParent>
  searchUsers?: QueryToSearchUsersResolver<TParent>
  verifyPasswordById?: QueryToVerifyPasswordByIdResolver<TParent>
}

export interface QueryToGetUserArgs {
  userId: string
}
export interface QueryToGetUserResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: QueryToGetUserArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface QueryToGetUserByMobileArgs {
  mobile: string
}
export interface QueryToGetUserByMobileResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: QueryToGetUserByMobileArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface QueryToGetUserByEmailArgs {
  email: string
}
export interface QueryToGetUserByEmailResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: QueryToGetUserByEmailArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface QueryToSearchUsersArgs {
  username?: string
  mobile?: string
  email?: string
  status?: string
  primaryOfficeId?: string
  locationId?: string
  count?: number
  skip?: number
  sort?: string
}
export interface QueryToSearchUsersResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: QueryToSearchUsersArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface QueryToVerifyPasswordByIdArgs {
  id: string
  password: string
}
export interface QueryToVerifyPasswordByIdResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: QueryToVerifyPasswordByIdArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLMutationTypeResolver<TParent = any> {
  createOrUpdateUser?: MutationToCreateOrUpdateUserResolver<TParent>
  activateUser?: MutationToActivateUserResolver<TParent>
  changePassword?: MutationToChangePasswordResolver<TParent>
  changePhone?: MutationToChangePhoneResolver<TParent>
  changeEmail?: MutationToChangeEmailResolver<TParent>
  changeAvatar?: MutationToChangeAvatarResolver<TParent>
  auditUser?: MutationToAuditUserResolver<TParent>
  resendInvite?: MutationToResendInviteResolver<TParent>
  usernameReminder?: MutationToUsernameReminderResolver<TParent>
  resetPasswordInvite?: MutationToResetPasswordInviteResolver<TParent>
}

export interface MutationToCreateOrUpdateUserArgs {
  user: GQLUserInput
}
export interface MutationToCreateOrUpdateUserResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToCreateOrUpdateUserArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToActivateUserArgs {
  userId: string
  password: string
  securityQNAs: Array<GQLSecurityQuestionAnswer | null>
}
export interface MutationToActivateUserResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: MutationToActivateUserArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToChangePasswordArgs {
  userId: string
  existingPassword: string
  password: string
}
export interface MutationToChangePasswordResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToChangePasswordArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToChangePhoneArgs {
  userId: string
  phoneNumber: string
  nonce: string
  verifyCode: string
}
export interface MutationToChangePhoneResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: MutationToChangePhoneArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToChangeEmailArgs {
  userId: string
  email: string
  nonce: string
  verifyCode: string
}
export interface MutationToChangeEmailResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: MutationToChangeEmailArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToChangeAvatarArgs {
  userId: string
  avatar: GQLAvatarInput
}
export interface MutationToChangeAvatarResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: MutationToChangeAvatarArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToAuditUserArgs {
  userId: string
  action: string
  reason: string
  comment?: string
}
export interface MutationToAuditUserResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: MutationToAuditUserArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToResendInviteArgs {
  userId: string
}
export interface MutationToResendInviteResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: MutationToResendInviteArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToUsernameReminderArgs {
  userId: string
}
export interface MutationToUsernameReminderResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToUsernameReminderArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface MutationToResetPasswordInviteArgs {
  userId: string
}
export interface MutationToResetPasswordInviteResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: MutationToResetPasswordInviteArgs,
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLDummyTypeResolver<TParent = any> {
  dummy?: DummyToDummyResolver<TParent>
}

export interface DummyToDummyResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLUserTypeResolver<TParent = any> {
  id?: UserToIdResolver<TParent>
  name?: UserToNameResolver<TParent>
  username?: UserToUsernameResolver<TParent>
  mobile?: UserToMobileResolver<TParent>
  role?: UserToRoleResolver<TParent>
  email?: UserToEmailResolver<TParent>
  fullHonorificName?: UserToFullHonorificNameResolver<TParent>
  status?: UserToStatusResolver<TParent>
  primaryOfficeId?: UserToPrimaryOfficeIdResolver<TParent>
  signature?: UserToSignatureResolver<TParent>
  avatar?: UserToAvatarResolver<TParent>
}

export interface UserToIdResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToNameResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToUsernameResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToMobileResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToRoleResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToEmailResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToFullHonorificNameResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToStatusResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToPrimaryOfficeIdResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToSignatureResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface UserToAvatarResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLSearchUserResultTypeResolver<TParent = any> {
  results?: SearchUserResultToResultsResolver<TParent>
  totalItems?: SearchUserResultToTotalItemsResolver<TParent>
}

export interface SearchUserResultToResultsResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface SearchUserResultToTotalItemsResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLVerifyPasswordResultTypeResolver<TParent = any> {
  mobile?: VerifyPasswordResultToMobileResolver<TParent>
  scrope?: VerifyPasswordResultToScropeResolver<TParent>
  status?: VerifyPasswordResultToStatusResolver<TParent>
  username?: VerifyPasswordResultToUsernameResolver<TParent>
  id?: VerifyPasswordResultToIdResolver<TParent>
}

export interface VerifyPasswordResultToMobileResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface VerifyPasswordResultToScropeResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface VerifyPasswordResultToStatusResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface VerifyPasswordResultToUsernameResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface VerifyPasswordResultToIdResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLAvatarTypeResolver<TParent = any> {
  type?: AvatarToTypeResolver<TParent>
  data?: AvatarToDataResolver<TParent>
}

export interface AvatarToTypeResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface AvatarToDataResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLHumanNameTypeResolver<TParent = any> {
  use?: HumanNameToUseResolver<TParent>
  firstNames?: HumanNameToFirstNamesResolver<TParent>
  middleName?: HumanNameToMiddleNameResolver<TParent>
  familyName?: HumanNameToFamilyNameResolver<TParent>
  marriedLastName?: HumanNameToMarriedLastNameResolver<TParent>
}

export interface HumanNameToUseResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface HumanNameToFirstNamesResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface HumanNameToMiddleNameResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface HumanNameToFamilyNameResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface HumanNameToMarriedLastNameResolver<
  TParent = any,
  TResult = any
> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface GQLSignatureTypeResolver<TParent = any> {
  data?: SignatureToDataResolver<TParent>
  type?: SignatureToTypeResolver<TParent>
}

export interface SignatureToDataResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}

export interface SignatureToTypeResolver<TParent = any, TResult = any> {
  (
    parent: TParent,
    args: {},
    context: Context,
    info: GraphQLResolveInfo
  ): TResult
}
