-- Up Migration
CREATE EXTENSION mongo_fdw;

CREATE SERVER mongo FOREIGN DATA WRAPPER mongo_fdw OPTIONS(
  address '${MONGO_HOST}',
  port '${MONGO_PORT}'
);

GRANT USAGE ON FOREIGN SERVER mongo TO ${EVENTS_MIGRATION_USER};

CREATE USER MAPPING FOR ${EVENTS_MIGRATION_USER} SERVER mongo;

-- Down Migration
DROP USER MAPPING FOR ${EVENTS_MIGRATION_USER} SERVER mongo;

DROP SERVER mongo CASCADE;

DROP EXTENSION mongo_fdw CASCADE;
