// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum app.action_status */
type ActionStatus = 'Requested' | 'Accepted' | 'Rejected'

export default ActionStatus
