// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.administrative_areas */
export default interface AdministrativeAreasTable {
  id: ColumnType<UUID, UUID, UUID>

  name: ColumnType<string, string, string>

  parentId: ColumnType<UUID | null, UUID | null, UUID | null>

  createdAt: ColumnType<string, string | undefined, string>

  updatedAt: ColumnType<string, string | undefined, string>

  deletedAt: ColumnType<string | null, string | null, string | null>

  validUntil: ColumnType<string | null, string | null, string | null>
}

export type AdministrativeAreas = Selectable<AdministrativeAreasTable>

export type NewAdministrativeAreas = Insertable<AdministrativeAreasTable>

export type AdministrativeAreasUpdate = Updateable<AdministrativeAreasTable>
