// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as EventActionDraftsTable } from './EventActionDrafts'
import type { default as LocationsTable } from './Locations'
import type { default as UserCredentialsTable } from './UserCredentials'
import type { default as NotificationsTable } from './Notifications'
import type { default as SystemClientsTable } from './SystemClients'
import type { default as AdministrativeAreasTable } from './AdministrativeAreas'
import type { default as EventActionsTable } from './EventActions'
import type { default as AuditLogTable } from './AuditLog'
import type { default as UsersTable } from './Users'
import type { default as EventsTable } from './Events'

export default interface AppSchema {
  eventActionDrafts: EventActionDraftsTable

  locations: LocationsTable

  userCredentials: UserCredentialsTable

  notifications: NotificationsTable

  systemClients: SystemClientsTable

  administrativeAreas: AdministrativeAreasTable

  eventActions: EventActionsTable

  auditLog: AuditLogTable

  users: UsersTable

  events: EventsTable
}
