// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as EventActionDraftsTable } from './EventActionDrafts'
import type { default as EventActionsTable } from './EventActions'
import type { default as LocationsTable } from './Locations'
import type { default as EventsTable } from './Events'

export default interface AppSchema {
  eventActionDrafts: EventActionDraftsTable

  eventActions: EventActionsTable

  locations: LocationsTable

  events: EventsTable
}
