// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { default as UserType } from './UserType'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/**
 * Represents the table app.audit_log
 * Stores an audit trail of operations performed by users and system integrations, including request data and a curated response summary.
 */
export default interface AuditLogTable {
  id: ColumnType<UUID, UUID | undefined, UUID>

  /** ID of the integration client or user making the request. */
  clientId: ColumnType<string, string, string>

  /** Whether the client is a human user or a system integration. */
  clientType: ColumnType<UserType, UserType, UserType>

  /** The operation that was performed. */
  operation: ColumnType<string, string, string>

  /** JSON blob of the request payload. */
  requestData: ColumnType<
    Record<string, any> | null,
    Record<string, any> | null,
    Record<string, any> | null
  >

  /** Per-endpoint curated summary of the response (e.g. search terms used and count + IDs of results returned). Not the raw response payload. */
  responseSummary: ColumnType<
    Record<string, any> | null,
    Record<string, any> | null,
    Record<string, any> | null
  >

  createdAt: ColumnType<string, string | undefined, string>
}

export type AuditLog = Selectable<AuditLogTable>

export type NewAuditLog = Insertable<AuditLogTable>

export type AuditLogUpdate = Updateable<AuditLogTable>
