// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/**
 * Represents the table app.events
 * Stores life events associated with individuals, identified by tracking_id. Each event includes a type, structured data payload, and a client-supplied transaction_id to ensure idempotency.
 */
export default interface EventsTable {
  id: ColumnType<UUID, UUID | undefined, UUID>

  eventType: ColumnType<string, string, string>

  transactionId: ColumnType<string, string, string>

  trackingId: ColumnType<string, string, string>

  createdAt: ColumnType<string, string | undefined, string>

  updatedAt: ColumnType<string, string | undefined, string>
}

export type Events = Selectable<EventsTable>

export type NewEvents = Insertable<EventsTable>

export type EventsUpdate = Updateable<EventsTable>
