// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { default as ActionType } from './ActionType'
import type { default as UserType } from './UserType'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/**
 * Represents the table app.event_action_drafts
 * Stores user-specific drafts of event-related actions. Drafts use client-supplied transaction_id for idempotency. Declaration fields may be incomplete. Each draft is owned exclusively by created_by.
 */
export default interface EventActionDraftsTable {
  id: ColumnType<UUID, UUID | undefined, UUID>

  transactionId: ColumnType<string, string, string>

  eventId: ColumnType<UUID, UUID, UUID>

  actionType: ColumnType<ActionType, ActionType, ActionType>

  declaration: ColumnType<
    Record<string, any>,
    Record<string, any> | undefined,
    Record<string, any>
  >

  annotation: ColumnType<
    Record<string, any> | null,
    Record<string, any> | null,
    Record<string, any> | null
  >

  createdBy: ColumnType<string, string, string>

  createdByRole: ColumnType<string, string, string>

  createdByUserType: ColumnType<UserType, UserType, UserType>

  createdBySignature: ColumnType<string | null, string | null, string | null>

  createdAtLocation: ColumnType<UUID, UUID, UUID>

  createdAt: ColumnType<string, string | undefined, string>
}

export type EventActionDrafts = Selectable<EventActionDraftsTable>

export type NewEventActionDrafts = Insertable<EventActionDraftsTable>

export type EventActionDraftsUpdate = Updateable<EventActionDraftsTable>
