// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum app.location_type */
type LocationType = 'HEALTH_FACILITY' | 'CRVS_OFFICE' | 'ADMIN_STRUCTURE'

export default LocationType
