// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { default as LocationType } from './LocationType'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.locations */
export default interface LocationsTable {
  id: ColumnType<UUID, UUID, UUID>

  name: ColumnType<string, string, string>

  parentId: ColumnType<UUID | null, UUID | null, UUID | null>

  createdAt: ColumnType<string, string | undefined, string>

  updatedAt: ColumnType<string, string | undefined, string>

  deletedAt: ColumnType<string | null, string | null, string | null>

  locationType: ColumnType<
    LocationType | null,
    LocationType | null,
    LocationType | null
  >

  validUntil: ColumnType<string | null, string | null, string | null>
}

export type Locations = Selectable<LocationsTable>

export type NewLocations = Insertable<LocationsTable>

export type LocationsUpdate = Updateable<LocationsTable>
