// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.migration_progress */
export default interface MigrationProgressTable {}

export type MigrationProgress = Selectable<MigrationProgressTable>

export type NewMigrationProgress = Insertable<MigrationProgressTable>

export type MigrationProgressUpdate = Updateable<MigrationProgressTable>
