// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.notifications */
export default interface NotificationsTable {
  id: ColumnType<UUID, UUID | undefined, UUID>

  subject: ColumnType<string, string, string>

  body: ColumnType<string, string, string>

  locale: ColumnType<string, string | undefined, string>

  /** All BCC recipient emails, snapshotted at creation time. */
  recipients: ColumnType<string[], string[], string[]>

  createdBy: ColumnType<UUID, UUID, UUID>

  createdAt: ColumnType<string, string | undefined, string>

  status: ColumnType<string, string | undefined, string>

  /** Number of recipients sent so far. Worker resumes from this offset on retry. */
  progress: ColumnType<number, number | undefined, number>

  retryCount: ColumnType<number, number | undefined, number>

  error: ColumnType<
    Record<string, any> | null,
    Record<string, any> | null,
    Record<string, any> | null
  >

  sentAt: ColumnType<string | null, string | null, string | null>
}

export type Notifications = Selectable<NotificationsTable>

export type NewNotifications = Insertable<NotificationsTable>

export type NotificationsUpdate = Updateable<NotificationsTable>
