// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table app.pgmigrations */
export default interface PgmigrationsTable {
}

export type Pgmigrations = Selectable<PgmigrationsTable>;

export type NewPgmigrations = Insertable<PgmigrationsTable>;

export type PgmigrationsUpdate = Updateable<PgmigrationsTable>;
