// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.pgmigrations_legacy_data */
export default interface PgmigrationsLegacyDataTable {}

export type PgmigrationsLegacyData = Selectable<PgmigrationsLegacyDataTable>

export type NewPgmigrationsLegacyData = Insertable<PgmigrationsLegacyDataTable>

export type PgmigrationsLegacyDataUpdate =
  Updateable<PgmigrationsLegacyDataTable>
