// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum app.status_type */
type StatusType = 'pending' | 'active' | 'deactivated'

export default StatusType
