// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/**
 * Represents the table app.system_initialisation
 * Single-row table tracking application initialisation state. Populated once during initial migration, and never modified except to mark initialisation as completed.
 */
export default interface SystemInitialisationTable {
  id: ColumnType<number, number | undefined, number>

  hash: ColumnType<string | null, string | null, string | null>

  salt: ColumnType<string | null, string | null, string | null>

  completedAt: ColumnType<string | null, string | null, string | null>

  createdAt: ColumnType<string, string | undefined, string>
}

export type SystemInitialisation = Selectable<SystemInitialisationTable>

export type NewSystemInitialisation = Insertable<SystemInitialisationTable>

export type SystemInitialisationUpdate = Updateable<SystemInitialisationTable>
