// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.system_clients */
export default interface SystemClientsTable {
  id: ColumnType<UUID, UUID | undefined, UUID>

  legacyId: ColumnType<string | null, string | null, string | null>

  name: ColumnType<string, string, string>

  scopes: ColumnType<
    Record<string, any>,
    Record<string, any> | undefined,
    Record<string, any>
  >

  createdBy: ColumnType<string | null, string | null, string | null>

  secretHash: ColumnType<string | null, string | null, string | null>

  salt: ColumnType<string | null, string | null, string | null>

  shaSecret: ColumnType<string | null, string | null, string | null>

  status: ColumnType<string, string | undefined, string>

  createdAt: ColumnType<string, string | undefined, string>
}

export type SystemClients = Selectable<SystemClientsTable>

export type NewSystemClients = Insertable<SystemClientsTable>

export type SystemClientsUpdate = Updateable<SystemClientsTable>
