// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { default as StatusType } from './StatusType'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.users */
export default interface UsersTable {
  id: ColumnType<UUID, UUID | undefined, UUID>

  /** References the user id from the legacy database. */
  legacyId: ColumnType<string | null, string | null, string | null>

  firstname: ColumnType<string | null, string | null, string | null>

  surname: ColumnType<string | null, string | null, string | null>

  fullHonorificName: ColumnType<string | null, string | null, string | null>

  role: ColumnType<string, string, string>

  status: ColumnType<StatusType, StatusType, StatusType>

  email: ColumnType<string | null, string | null, string | null>

  mobile: ColumnType<string | null, string | null, string | null>

  signaturePath: ColumnType<string | null, string | null, string | null>

  profileImagePath: ColumnType<string | null, string | null, string | null>

  officeId: ColumnType<UUID, UUID, UUID>
}

export type Users = Selectable<UsersTable>

export type NewUsers = Insertable<UsersTable>

export type UsersUpdate = Updateable<UsersTable>
