// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.user_credentials */
export default interface UserCredentialsTable {
  id: ColumnType<UUID, UUID | undefined, UUID>

  userId: ColumnType<UUID, UUID, UUID>

  username: ColumnType<string, string, string>

  passwordHash: ColumnType<string, string, string>

  salt: ColumnType<string, string, string>

  securityQuestions: ColumnType<
    Record<string, any>,
    Record<string, any> | undefined,
    Record<string, any>
  >
}

export type UserCredentials = Selectable<UserCredentialsTable>

export type NewUserCredentials = Insertable<UserCredentialsTable>

export type UserCredentialsUpdate = Updateable<UserCredentialsTable>
