export default
  {
    code: 'birth-notification',
    tracking: 'BN-082cefe0-cab',
    uuid: '082cefe0-caba-11e7-aca8-91613b726b0e',
    mother_firstName: 'Mary',
    mother_middleName: 'Jane',
    mother_family: 'Mensah',
    mother_maidenName: 'Hamilton',
    mother_birthDate: '1985-11-22T20:09:47.084Z',
    mother_personalIDNummber: 'GH0909808',
    mother_maritalStatus: 'married',
    mother_marriageDate: '2016-11-22T20:09:47.084Z',
    mother_nationality: 'Ghana',
    mother_phone: '+447773165471',
    mother_email: 'mary.hamilton@google.com',
    mother_use: 'phone',
    mother_addressLine1: '96 Acacia Road',
    mother_addressLine2: '',
    mother_addressLine3: '',
    mother_city: 'Swedru',
    mother_county: 'Agona West Municipal',
    mother_postalCode: 'GH67',
    mother_state: 'Central Region',
    childrenBornAlive: '2',
    childrenBornLiving: '2',
    foetalDeaths: '0',
    birthDateLast: '2015-11-22T20:09:47.084Z',
    mother_gender: 'female',
    mother_religion: 'christian',
    mother_formalEducation: 'high',
    mother_occupation: 'Teacher',
    mother_employment: 'part-time',
    child_phone: '0173764383',
    firstName: 'David',
    middleName: 'Joshua',
    family: 'Mensah',
    birthDate: '2017-11-02T00:00:00.000Z',
    gender: 'male',
    child_email: '',
    child_use: '',
    child_addressLine1: '',
    child_addressLine2: '',
    child_addressLine3: '',
    child_city: 'Swedru',
    child_county: 'Agona West Municipal',
    child_postalCode: '',
    child_state: 'Central Region',
    placeOfDelivery: 'clinic',
    attendantAtBirth: 'Midwife',
    addressLine1: '168 Adeiso Road',
    addressLine2: '',
    addressLine3: '',
    city: 'Swedru',
    county: 'Agona West Municipal',
    hospitalName: 'Akai House Clinic',
    postalCode: 'GH23',
    state: 'Central Region',
    father_firstName: 'Michael',
    father_middleName: 'James',
    father_family: 'francis',
    father_birthDate: '1992-11-22T20:09:47.084Z',
    father_personalIDNummber: 'GH987',
    father_maritalStatus: 'married',
    father_marriageDate: '2016-11-22T20:09:47.084Z',
    father_nationality: 'Ghana',
    father_phone: '+447557394986',
    father_email: 'michael.francis@gmail.com',
    father_use: 'phone',
    father_addressLine1: '96 Acacia Road',
    father_addressLine2: '',
    father_addressLine3: '',
    father_city: 'Swedru',
    father_county: 'Agona West Municipal',
    father_postalCode: 'GH67',
    father_state: 'Central Region',
    father_gender: 'male',
    father_religion: 'christian',
    father_formalEducation: 'high',
    father_occupation: 'Teacher',
    father_employment: 'full-time',
    informant_firstName: 'Margaret',
    informant_middleName: 'Ray',
    informant_family: 'Robinson',
    informant_relationship: 'Mother of mother',
    informant_addressLine1: '67 Acacia Road',
    informant_addressLine2: '',
    informant_addressLine3: '',
    informant_city: 'Swedru',
    informant_county: 'Agona West Municipal',
    informant_state: 'Central Region',
    informant_postalCode: 'GH67',
    informant_personalIDNummber: 'GH989870',
    informant_email: 'margaret.robinson@gmail.com',
    informant_phone: '07885929949',
    typeOfBirth: 'twin'
  };

