export * from './field-mappings'
export * from '@register/forms/register/fieldDefinitions/birth/mappings/query/documents-mappings'
export * from '@register/forms/register/fieldDefinitions/birth/mappings/query/father-mappings'
export * from '@register/forms/register/fieldDefinitions/birth/mappings/query/registration-mappings'
export * from '@register/forms/register/fieldDefinitions/death/mappings/query/application-mappings'
export * from '@register/forms/register/fieldDefinitions/death/mappings/query/cause-of-death-mappings'
export * from '@register/forms/register/fieldDefinitions/death/mappings/query/documents-mappings'
export * from '@register/forms/register/fieldDefinitions/death/mappings/query/event-mappings'
