export * from './field-mappings'
export * from '@register/forms/register/fieldMappings/birth/query/documents-mappings'
export * from '@register/forms/register/fieldMappings/birth/query/father-mappings'
export * from '@register/forms/register/fieldMappings/birth/query/registration-mappings'
export * from '@register/forms/register/fieldMappings/death/query/application-mappings'
export * from '@register/forms/register/fieldMappings/death/query/cause-of-death-mappings'
export * from '@register/forms/register/fieldMappings/death/query/documents-mappings'
export * from '@register/forms/register/fieldMappings/death/query/event-mappings'
