{{- if .Values.mosip_api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mosip-api
spec:
  selector:
    app: mosip-api
  ports:
    - port: 2024
      targetPort: 2024
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mosip-api
spec:
  entryPoints:
  {{- if .Values.ingress.ssl_enabled }}
    - websecure
  {{- end }}
  {{- if or .Values.ingress.tls_resolver (not .Values.ingress.ssl_enabled) }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`mosip-api.{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: mosip-api
      namespace: {{ .Release.Namespace }}
      port: 2024
    middlewares:
      - name: sts-and-basic-response-headers
  {{- if .Values.ingress.tls_resolver }}
  tls:
    certResolver: {{ .Values.ingress.tls_resolver }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosip-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosip-api
  template:
    metadata:
      labels:
        app: mosip-api
    spec:
      containers:
        - name: mosip-api
          image: {{ .Values.mosip_api.image.repository }}:{{ .Values.mosip_api.image.tag }}
          env:
            - name: CLIENT_APP_URL
              value: {{ include "render-external-url" (dict "service_name" "register" "Values" .Values) }}
            - name: MOSIP_WEBSUB_CALLBACK_URL
              value: http://mosip-api.{{ .Release.Namespace }}.svc.cluster.local:2024/websub/callback
            - name: MOSIP_WEBSUB_HUB_URL
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/websub/hub
            - name: MOSIP_CREATE_PACKET_URL
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/commons/v1/packetmanager/createPacket
            - name: MOSIP_PROCESS_PACKET_URL
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/registrationprocessor/v1/workflowmanager/workflowinstance
            - name: MOSIP_VERIFIABLE_CREDENTIAL_ALLOWLIST
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/.well-known/public-key.json
            - name: MOSIP_AUTH_URL
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/v1/authmanager/authenticate/clientidsecretkey
            - name: IDA_AUTH_DOMAIN_URI
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/
            - name: IDA_AUTH_URL
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/idauthentication/v1/auth
            - name: ESIGNET_USERINFO_URL
              value: http://esignet-mock.{{ .Release.Namespace }}.svc.cluster.local:20260/oidc/userinfo
            - name: ESIGNET_TOKEN_URL
              value: http://esignet-mock.{{ .Release.Namespace }}.svc.cluster.local:20260/oauth/token
            - name: MOSIP_BIRTH_WEBHOOK_URL
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/webhooks/opencrvs/birth
            - name: MOSIP_DEATH_WEBHOOK_URL
              value: http://mosip-mock.{{ .Release.Namespace }}.svc.cluster.local:20240/webhooks/opencrvs/death
            - name: OPENCRVS_GATEWAY_URL
              value: http://gateway.{{ .Release.Namespace }}.svc.cluster.local:7070
            - name: OPENCRVS_PUBLIC_KEY_URL
              value: http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040/.well-known
          {{- include "render-env-vars" (dict "service_name" "mosip_api" "Values" .Values) }}
          volumeMounts:
            - name: keystore
              mountPath: /certs
      volumes:
        - name: keystore
          secret:
            secretName: mosip-certs
{{- end }}
