// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as AppSchema } from './app/AppSchema'

type Database = AppSchema

export default Database
