UPDATE
  PUBLIC.SETTING
SET
  "VALUE" = '$OPENCRVS_METABASE_SITE_NAME'
WHERE
  "KEY" = 'site-name';

UPDATE
  PUBLIC.SETTING
SET
  "VALUE" = '$OPENCRVS_METABASE_SITE_URL'
WHERE
  "KEY" = 'site-url';

UPDATE
  PUBLIC.SETTING
SET
  "VALUE" = '{"cdc1d5eb-c7f8-8b01-b296-eda34d06b6da":{"name":"$OPENCRVS_METABASE_MAP_NAME","url":"$OPENCRVS_METABASE_MAP_URL","region_key":"$OPENCRVS_METABASE_MAP_REGION_KEY","region_name":"$OPENCRVS_METABASE_MAP_REGION_NAME"}}'
WHERE
  "KEY" = 'custom-geojson';

UPDATE
  PUBLIC.METABASE_DATABASE
SET
  DETAILS = '{"ssl": $METABASE_DATABASE_SSL,"password":"$METABASE_DATABASE_PASSWORD","destination-database":false,"port":$METABASE_DATABASE_PORT,"advanced-options":false,"schema-filters-type":"all","dbname":"$METABASE_DATABASE_NAME","host":"$METABASE_DATABASE_HOST","tunnel-enabled": false,"user":"$METABASE_DATABASE_USER"}'
WHERE
  NAME = 'OpenCRVS Analytics Database';

UPDATE
  PUBLIC.CORE_USER
SET
  EMAIL = '$OPENCRVS_METABASE_ADMIN_EMAIL',
  PASSWORD = '$OPENCRVS_METABASE_ADMIN_PASSWORD_HASH',
  PASSWORD_SALT = '$OPENCRVS_METABASE_ADMIN_PASSWORD_SALT'
WHERE
 IS_SUPERUSER = true;