mode: deployment

image:
  repository: otel/opentelemetry-collector-k8s

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    prometheus: null
    jaeger: null
    zipkin: null

  exporters:
    otlp/elastic:
      endpoint: apm-server.opencrvs-deps-{{env}}.svc.cluster.local:8200
      tls:
        insecure: true
  processors:
    batch:
      timeout: 15s
      send_batch_size: 1024

    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

  service:
    telemetry:
      metrics:
        level: none
        readers: null
    pipelines:
      logs: null
      metrics:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - otlp/elastic
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - otlp/elastic
