export const APPLICATIONS_STATUS = 'applications'
export const REJECTED_STATUS = 'rejected'
export const NOTIFICATION_STATUS = 'notifications'
export const CERTIFICATE_MONEY_RECEIPT_DATE_FORMAT = 'DD.MM.YYYY'
export const CERTIFICATE_DATE_FORMAT = 'DD MMMM YYYY'
