
{{/*
FIXME: Revise usage of elasticsearch secrets once this bug is resolved:
https://github.com/opencrvs/opencrvs-core/issues/9657
*/}}
{{- if eq .Values.elasticsearch.auth_mode "auto" }}
{{/* Prevent secret mutation between helm upgrades */}}

{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.elasticsearch.users_secret }}
{{- if not $secret }}
{{- $secrets := dict }}
{{- $elastic_hosts := dict }}
{{- $elastic_urls := dict }}

{{- range $user_props := .Values.elasticsearch.auth_users }}
  {{- $user_key_val := split ":" $user_props }}
  {{- $prefix := $user_key_val._0 }}
  {{- $username := $user_key_val._1 | default $prefix }}
  {{- $password := randAlphaNum 32 }}
  {{- $host := printf "%s:%s@%s:%s" $username $password $.Values.elasticsearch.host ($.Values.elasticsearch.port | toString) }}

  {{- $_ := set $secrets (printf "%s_ELASTIC_USERNAME" $prefix) $username }}
  {{- $_ := set $secrets (printf "%s_ELASTIC_PASSWORD" $prefix) $password }}
  {{- $_ := set $elastic_hosts (printf "%s_ELASTIC_HOST" $prefix) $host }}
  {{- $_ := set $elastic_urls (printf "%s_ELASTIC_URL" $prefix) (printf "http://%s" $host) }}
{{- end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.users_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.urls_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- range $key, $val := $elastic_urls }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- range $key, $val := $elastic_hosts }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
{{- end }}