{{- if eq .Values.elasticsearch.auth_mode "auto" }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  labels:
    app: elasticsearch-on-deploy
  name: elasticsearch-on-deploy
spec:
  template:
    metadata:
      labels:
        app: elasticsearch-on-deploy
    spec:
      containers:
        - name: elasticsearch-on-deploy
          command: ["/scripts/setup.sh"]
          image: "bash"
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.elasticsearch.host }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.admin_user_secret_name }}
                  key: ELASTIC_PASSWORD
            - name: SEARCH_ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.users_secret }}
                  key: SEARCH_ELASTIC_USERNAME
            - name: SEARCH_ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.users_secret }}
                  key: SEARCH_ELASTIC_PASSWORD
          volumeMounts:
            - mountPath: /scripts
              name: elasticsearch-on-update-script
      volumes:
        - name: elasticsearch-on-update-script
          configMap:
            name: elasticsearch-on-update-script
            defaultMode: 0755
      restartPolicy: "OnFailure"
{{- end }}
