---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events
    service_name: opencrvs_events
  name: events
spec:
  replicas: {{ .Values.events.replicas | default 1 }}
  {{- include "strategy-helper" (dict "service_name" "events" "Values" .Values) | indent 2 }}
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      annotations:
        lastdeploy-timestamp: {{ now | quote }}
      labels:
        app: events
        service_name: opencrvs_events
    spec:
      {{- include "opencrvs.imagePullSecrets" (dict "root" . "service" .Values.events) | nindent 6 }}
      {{- include "pod-service-account-values-helper" (dict "service_name" "events" "Values" .Values) | nindent 6 }}
      containers:
        - name: events
          image: {{ include "opencrvs.image" (dict "root" . "service" .Values.events) }}
          imagePullPolicy: {{ .Values.events.image.pullPolicy | default .Values.platform.imagePullPolicy }}
          env:
          {{- include "render-otel-env-vars" (dict "Values" .Values "Release" .Release) }}
            - name: AUTH_URL
              value: "http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040"
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: COUNTRY_CONFIG_URL
              value: "http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040"
            - name: DOCUMENTS_URL
              value: "http://documents.{{ .Release.Namespace }}.svc.cluster.local:9050"
          {{- if eq .Values.elasticsearch.auth_mode "disabled" }}
            - name: ES_URL
              value: "http://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
          {{- else if or (eq .Values.elasticsearch.auth_mode "auto") (eq .Values.elasticsearch.auth_mode "use_secret") }}
            - name: ES_URL
              valueFrom:
                secretKeyRef:
                  key: SEARCH_ELASTIC_URL
                  name: {{ .Values.elasticsearch.urls_secret }}
          {{- end }}
          {{- if not (eq .Values.postgres.auth_mode "managed") }}
            - name: EVENTS_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  key: events_app_db_url
                  name: {{ .Values.postgres.urls_secret }}
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "events" "Values" .Values) }}
          {{- include "resources-helper" (dict "service_name" "events" "Values" .Values) | indent 10 }}
          {{- include "probes-helper" (dict "service_name" "events" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.events.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - name: public-key
          configMap:
            name: {{ .Release.Name }}-cert-tls
            items:
              - key: public-key.pem
                path: public-key.pem

{{- include "service-account-helper" (dict "service_name" "events" "Values" .Values) }}

{{- include "service-helper" (dict "service_name" "events" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "events" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "events" "Values" .Values) }}
