---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: login-route
spec:
  entryPoints:
  {{- if or .Values.ingress.ssl_enabled .Values.ingress.tls_resolver }}
    - websecure
  {{- end }}
  {{- if or .Values.ingress.tls_resolver (not .Values.ingress.ssl_enabled) }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`{{ include "render-external-subdomain" (dict "service_name" "login" "Values" .Values) }}`) || Host(`{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: login
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.login.port }}
    middlewares:
      - name: sts-and-basic-response-headers
      - name: enable-compression
  {{- if .Values.ingress.tls_resolver }}
  tls:
    certResolver: {{ .Values.ingress.tls_resolver }}
  {{- else if .Values.ingress.tls_secret_name }}
  tls:
    secretName: {{ .Values.ingress.tls_secret_name }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login
  name: login
spec:
  replicas: {{ .Values.login.replicas | default 1 }}
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      {{- include "opencrvs.imagePullSecrets" (dict "root" . "service" .Values.login) | nindent 6 }}
      containers:
        - name: login
          image: {{ include "opencrvs.image" (dict "root" . "service" .Values.login) }}
          env:
          {{- if and
            (not (hasKey (.Values.login.env | default dict) "CONTENT_SECURITY_POLICY_WILDCARD"))
            (not (hasKey (.Values.env | default dict) "CONTENT_SECURITY_POLICY_WILDCARD"))
          }}
            - name: CONTENT_SECURITY_POLICY_WILDCARD
              value: "*.{{ .Values.hostname }}"
          {{- end }}
            - name: COUNTRY_CONFIG_URL_INTERNAL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
            - name: CLIENT_APP_URL
              value: {{ include "render-external-url" (dict "service_name" "register" "Values" .Values) }}
            - name: AUTH_URL_INTERNAL
              value: http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040
            - name: GATEWAY_URL_INTERNAL
              value: http://gateway.{{ .Release.Namespace }}.svc.cluster.local:7070
          {{- include "render-env-vars" (dict "service_name" "login" "Values" .Values) }}
          {{- include "resources-helper" (dict "service_name" "login" "Values" .Values) | indent 10 }}
          {{- include "probes-helper" (dict "service_name" "login" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.login.port }}
              protocol: TCP
          {{- if .Values.client.nginx_conf_d_configmaps }}
          volumeMounts:
          {{- range $config_name := .Values.login.nginx_conf_d_configmaps }}
            - name: {{ $config_name }}
              mountPath: /etc/nginx/conf.d/{{ $config_name }}.conf
              subPath: "{{ $config_name }}.conf"
          {{- end }}
          {{- end }}
      restartPolicy: Always
      {{- if .Values.login.nginx_conf_d_configmaps }}
      volumes:
      {{- range $config_name := .Values.login.nginx_conf_d_configmaps }}
        - name: {{ $config_name }}
          configMap:
            name: {{ $config_name }}
      {{- end }}
      {{- end }}

{{- include "service-helper" (dict "service_name" "login" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "login" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "login" "Values" .Values) }}
