
{{- if eq .Values.mongodb.auth_mode "auto" }}
{{/* Prevent secret mutation between helm upgrades */}}

{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.mongodb.users_secret }}
{{- if not $secret }}

{{- $passwords := dict }}
{{- $mongo_db_urls := dict }}

{{- range .Values.mongodb.databases }}
  {{- $password := randAlphaNum 32 }}
  {{- $db_url := printf "mongodb://%s:%s@%s:27017/%s" .user $password $.Values.mongodb.host .db }}

  {{- $_ := set $passwords (printf "%s_MONGODB_PASSWORD" .prefix) $password }}
  {{- $_ := set $passwords (printf "%s_MONGODB_USER" .prefix) .user }}
  {{- $_ := set $passwords (printf "%s_MONGODB_DB" .prefix) .db }}
  {{- $_ := set $passwords (printf "%s_MONGODB_ROLES" .prefix) (.roles | quote) }}
  {{- $_ := set $mongo_db_urls (printf "%s_MONGO_URL" .prefix) $db_url }}
{{- end }}

{{/*
MognoDB regular users (per database)
Secret is used to create users and assign appropriate roles
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.users_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- range $key, $val := $passwords }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.urls_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- range $key, $val := $mongo_db_urls }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

{{- end }}
{{- end }}
