
{{- if or (eq .Values.postgres.auth_mode "auto") (eq .Values.postgres.auth_mode "disabled") }}

{{- $passwords := dict }}
{{- $postgres_db_urls := dict }}

{{- $POSTGRES_USER := "postgres" }}
{{- $POSTGRES_PASSWORD := "postgres" }}

{{- $postgres_admin_secret := lookup "v1" "Secret" .Release.Namespace .Values.postgres.admin_user_secret_name }}
{{- if $postgres_admin_secret }}
  {{- $POSTGRES_USER = (index $postgres_admin_secret.data "POSTGRES_USER" | b64dec) }}
  {{- $POSTGRES_PASSWORD = (index $postgres_admin_secret.data "POSTGRES_PASSWORD" | b64dec) }}
{{- end }}

{{- $EVENTS_APP_POSTGRES_PASSWORD := randAlphaNum 32 }}
{{- $EVENTS_MIGRATOR_POSTGRES_PASSWORD := randAlphaNum 32 }}
{{- $EVENTS_ANALYTICS_POSTGRES_PASSWORD := randAlphaNum 32 }}
{{- if eq .Values.postgres.auth_mode "disabled" }}
  {{- $EVENTS_APP_POSTGRES_PASSWORD = "password" }}
  {{- $EVENTS_MIGRATOR_POSTGRES_PASSWORD = "password" }}
  {{- $EVENTS_ANALYTICS_POSTGRES_PASSWORD = "password" }}
{{- end }}
{{- $EVENTS_APP_POSTGRES_USER := $.Values.postgres.events_app }}
{{- $EVENTS_MIGRATOR_POSTGRES_USER := $.Values.postgres.events_migrator }}
{{- $EVENTS_ANALYTICS_POSTGRES_USER := $.Values.postgres.events_analytics }}
{{- $_ := set $passwords "EVENTS_APP_POSTGRES_USER" $EVENTS_APP_POSTGRES_USER }}
{{- $_ := set $passwords "EVENTS_APP_POSTGRES_PASSWORD" $EVENTS_APP_POSTGRES_PASSWORD }}
{{- $_ := set $passwords "EVENTS_MIGRATOR_POSTGRES_USER" $EVENTS_MIGRATOR_POSTGRES_USER }}
{{- $_ := set $passwords "EVENTS_MIGRATOR_POSTGRES_PASSWORD" $EVENTS_MIGRATOR_POSTGRES_PASSWORD }}
{{- $_ := set $passwords "EVENTS_ANALYTICS_POSTGRES_USER" $EVENTS_ANALYTICS_POSTGRES_USER }}
{{- $_ := set $passwords "EVENTS_ANALYTICS_POSTGRES_PASSWORD" $EVENTS_ANALYTICS_POSTGRES_PASSWORD }}
{{- $EVENTS_DB := $.Values.postgres.events_db }}
{{- $_ := set $postgres_db_urls "events_app_db_url" (printf "postgres://%s:%s@%s:5432/%s?sslmode=%s" $EVENTS_APP_POSTGRES_USER $EVENTS_APP_POSTGRES_PASSWORD $.Values.postgres.host $EVENTS_DB $.Values.postgres.sslmode ) }}
{{- $_ := set $postgres_db_urls "events_migrator_db_url" (printf "postgres://%s:%s@%s:5432/%s?sslmode=%s" $EVENTS_MIGRATOR_POSTGRES_USER $EVENTS_MIGRATOR_POSTGRES_PASSWORD $.Values.postgres.host $EVENTS_DB $.Values.postgres.sslmode ) }}
{{- $_ := set $postgres_db_urls "events_superuser_db_url" (printf "postgres://%s:%s@%s:5432/%s?sslmode=%s" $POSTGRES_USER $POSTGRES_PASSWORD $.Values.postgres.host $EVENTS_DB $.Values.postgres.sslmode ) }}
{{- $_ := set $postgres_db_urls "events_analytics_db_url" (printf "postgres://%s:%s@%s:5432/%s?sslmode=%s" $EVENTS_ANALYTICS_POSTGRES_USER $EVENTS_ANALYTICS_POSTGRES_PASSWORD $.Values.postgres.host $EVENTS_DB $.Values.postgres.sslmode ) }}

{{/*
Postgres regular users (per database)
Secret is used to create users and assign appropriate roles
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.users_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- range $key, $val := $passwords }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.urls_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- range $key, $val := $postgres_db_urls }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}

{{- end }}
