{{- if and .Values.validation.enabled .Values.validation.postdeploy.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
  labels:
    app: deployment-jobs
  name: validate-postdeploy
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.validation.active_deadline_seconds }}
  template:
    metadata:
      labels:
        app: deployment-jobs
        helm.sh/revision: {{ .Release.Revision | quote }}
    spec:
      {{- include "opencrvs.imagePullSecrets" (dict "root" . "service" .Values.utilities) | nindent 6 }}
      {{- include "pod-service-account-values-helper" (dict "service_name" "deployment-jobs" "Values" .Values) | nindent 6 }}
      containers:
        {{- include "opencrvs-validate.containerSpec" (dict "root" . "mode" "postdeploy") | nindent 8 }}
      restartPolicy: "Never"
{{- end }}
