# OpenCRVS Kubernetes shortcuts
# Generated by `yarn environment:configure-shell`.
# Do not edit this file, it is overwritten when the command runs again.

# Kubernetes shortcuts
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgs='kubectl get svc'
alias kgn='kubectl get nodes'
alias kga='kubectl get all'
alias kdp='kubectl describe pod'
alias kl='kubectl logs'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'


# Kubernetes functions
# Aliases take precedence over functions, e.g. the oh-my-zsh kubectl plugin defines kpf
unalias kexec klogs kns kpf 2>/dev/null

function kexec() {
    if [ -z "$1" ]; then
        echo "Usage: kexec <pod-name> [container-name]"
        return 1
    fi
    if [ -n "$2" ]; then
        kubectl exec -it $1 -c $2 -- bash
    else
        kubectl exec -it $1 -- bash
    fi
}

function klogs() {
    if [ -z "$1" ]; then
        echo "Usage: klogs <pod-name> [container-name]"
        return 1
    fi
    if [ -n "$2" ]; then
        kubectl logs -f $1 -c $2
    else
        kubectl logs -f $1
    fi
}

function kns() {
    if [ -z "$1" ]; then
        kubectl config view --minify --output 'jsonpath={..namespace}'; echo
    else
        kubectl config set-context --current --namespace=$1
    fi
}

function kpf() {
    kubectl port-forward $1 $2:$3
}

# Add a kubeconfig copied from an OpenCRVS server to ~/.kube/config
alias add-k8s-context='node "__OPENCRVS_TOOLKIT_CLI__" environment add-k8s-context'
