hostname: opencrvs.localhost
ingress:
  ssl_enabled: false
mosip_mock:
  enabled: true
  image:
    repository: ghcr.io/opencrvs/mosip-mock
    tag: 2.0.0-rc.6
  env:
    FOO: bar
    SENDER_EMAIL_ADDRESS: "test@opencrvs.org"
    ALERT_EMAIL: "test@opencrvs.org"
    SMTP_HOST: ""
    SMTP_PORT: 575
    SMTP_USERNAME: opencrvs
    SMTP_PASSWORD: ""
    SMTP_SECURE: true
    MOSIP_WEBSUB_TOPIC: CREDENTIAL_ISSUED

esignet_mock:
  enabled: true
  image:
    repository: ghcr.io/opencrvs/esignet-mock
    tag: 2.0.0-rc.6
  env:
    OIDP_CLIENT_PRIVATE_KEY_PATH: /certs/esignet-jwk.txt

mosip_api:
  enabled: true
  image:
    repository: ghcr.io/opencrvs/mosip-api
    tag: 2.0.0-rc.6
  env:
    LOCALE: en
    OIDP_CLIENT_PRIVATE_KEY_PATH: /certs/esignet-jwk.txt
    OPENID_PROVIDER_CLAIMS: name,family_name,given_name,middle_name,birthdate,address
    DECRYPT_P12_FILE_PATH: /certs/keystore.p12
    DECRYPT_P12_FILE_PASSWORD: mosip123
    ENCRYPT_CERT_PATH: /certs/ida-partner.crt
    PARTNER_APIKEY: 123456
    PARTNER_ID: aaaaaAAAAAbbbbbBBBBBcccccCCCCCdddddDDDDD
    PARTNER_MISP_LK: crvs-partner
    SIGN_P12_FILE_PATH: /certs/keystore.p12
    SIGN_P12_FILE_PASSWORD: mosip123
    SQLITE_DATABASE_PATH: /mosip-api.db
    MOSIP_AUTH_CLIENT_APP_ID: admin
    MOSIP_PACKET_AUTH_CLIENT_ID: mosip-regproc-client
    MOSIP_PACKET_AUTH_CLIENT_SECRET: abcdeABCDE123456
    MOSIP_WEBSUB_AUTH_CLIENT_ID: mosip-websub-client
    MOSIP_WEBSUB_AUTH_CLIENT_SECRET: abcdeABCDE123456
    MOSIP_WEBSUB_SECRET: mosip-websub-secret
    MOSIP_WEBSUB_TOPIC: CREDENTIAL_ISSUED
    MOSIP_CENTER_ID: 10123
    MOSIP_MACHINE_ID: 10234
