/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * OpenCRVS is also distributed under the terms of the Civil Registration
 * & Healthcare Disclaimer located at http://opencrvs.org/license.
 *
 * Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync
} from 'fs'
import { tmpdir } from 'os'
import path from 'path'
import * as yaml from 'js-yaml'
import {
  Kubeconfig,
  KubeconfigConflictError,
  addK8sContext,
  getLocalKubeconfigPath,
  mergeKubeconfig
} from './add-k8s-context'

// Shaped like the kubeconfig generated by server-setup/files/add-k8s-user.sh
function serverKubeconfig(user: string, host: string): Kubeconfig {
  const cluster = `public-k8s-${host}`
  return {
    apiVersion: 'v1',
    kind: 'Config',
    clusters: [
      {
        name: cluster,
        cluster: {
          'certificate-authority-data': `ca-${host}`,
          server: `https://${host}.example.org:6443`
        }
      }
    ],
    contexts: [{ name: `${user}@${cluster}`, context: { cluster, user } }],
    'current-context': `${user}@${cluster}`,
    users: [
      {
        name: user,
        user: {
          'client-certificate-data': `cert-${user}-${host}`,
          'client-key-data': `key-${user}-${host}`
        }
      }
    ]
  }
}

function conflictsOf(fn: () => unknown) {
  try {
    fn()
  } catch (err) {
    if (err instanceof KubeconfigConflictError) {
      return err.conflicts.map(({ label, name }) => `${label} ${name}`)
    }
    throw err
  }
  throw new Error('Expected a conflict')
}

describe('mergeKubeconfig', () => {
  it('creates a kubeconfig when there is none and uses the new context', () => {
    const source = serverKubeconfig('bob-qa', 'qa-01')
    const merged = mergeKubeconfig({}, source, 'config')

    expect(merged.apiVersion).toBe('v1')
    expect(merged.kind).toBe('Config')
    expect(merged.clusters).toEqual(source.clusters)
    expect(merged.contexts).toEqual(source.contexts)
    expect(merged.users).toEqual(source.users)
    expect(merged['current-context']).toBe('bob-qa@public-k8s-qa-01')
  })

  it('adds entries without changing existing ones or the current context', () => {
    const target = serverKubeconfig('bob-qa', 'qa-01')
    target.preferences = { colors: true }
    const merged = mergeKubeconfig(
      target,
      serverKubeconfig('bob-prod', 'prod-01'),
      'config'
    )

    expect(merged.contexts?.map(({ name }) => name)).toEqual([
      'bob-qa@public-k8s-qa-01',
      'bob-prod@public-k8s-prod-01'
    ])
    expect(merged.users?.map(({ name }) => name)).toEqual([
      'bob-qa',
      'bob-prod'
    ])
    expect(merged['current-context']).toBe('bob-qa@public-k8s-qa-01')
    expect(merged.preferences).toEqual({ colors: true })
  })

  it('handles sections kubectl left empty', () => {
    const merged = mergeKubeconfig(
      { clusters: null, contexts: null, users: null },
      serverKubeconfig('bob-qa', 'qa-01'),
      'config'
    )
    expect(merged.contexts).toHaveLength(1)
  })

  it('fails when the context already exists', () => {
    const source = serverKubeconfig('bob-qa', 'qa-01')
    expect(
      conflictsOf(() => mergeKubeconfig(source, source, 'config'))
    ).toEqual(['context bob-qa@public-k8s-qa-01'])
  })

  it('fails when a different user has the same name', () => {
    // Same environment name in two countries
    const target = serverKubeconfig('bob-qa', 'qa-01')
    const source = serverKubeconfig('bob-qa', 'qa-02')

    expect(
      conflictsOf(() => mergeKubeconfig(target, source, 'config'))
    ).toEqual(['user bob-qa'])
  })

  it('fails when a different cluster has the same name', () => {
    const target = serverKubeconfig('bob-qa', 'master')
    const source = serverKubeconfig('bob-prod', 'master')
    source.clusters![0].cluster = { server: 'https://other:6443' }

    expect(
      conflictsOf(() => mergeKubeconfig(target, source, 'config'))
    ).toEqual(['cluster public-k8s-master'])
  })

  it('reuses an identical cluster entry', () => {
    const target = serverKubeconfig('alice-qa', 'qa-01')
    const merged = mergeKubeconfig(
      target,
      serverKubeconfig('bob-qa', 'qa-01'),
      'config'
    )
    expect(merged.clusters).toHaveLength(1)
    expect(merged.contexts).toHaveLength(2)
  })

  it('explains how to remove the conflicting entries', () => {
    const source = serverKubeconfig('bob-qa', 'qa-01')
    expect(() =>
      mergeKubeconfig(source, source, '/home/bob/.kube/config')
    ).toThrowError(
      /Context already exists in \/home\/bob\/\.kube\/config[\s\S]*kubectl config delete-context bob-qa@public-k8s-qa-01/
    )
  })
})

describe('getLocalKubeconfigPath', () => {
  it('defaults to ~/.kube/config', () => {
    expect(getLocalKubeconfigPath({}, '/home/bob')).toBe(
      path.join('/home/bob', '.kube', 'config')
    )
  })

  it('uses the first existing file in KUBECONFIG', () => {
    const existing = __filename
    expect(
      getLocalKubeconfigPath(
        {
          KUBECONFIG: ['/does/not/exist', existing].join(path.delimiter)
        },
        '/home/bob'
      )
    ).toBe(existing)
  })
})

describe('addK8sContext', () => {
  let dir: string
  let sourcePath: string
  let targetPath: string

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), 'add-k8s-context-'))
    sourcePath = path.join(dir, 'kubeconfig')
    targetPath = path.join(dir, '.kube', 'config')
    writeFileSync(sourcePath, yaml.dump(serverKubeconfig('bob-qa', 'qa-01')))
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  const readTarget = () =>
    yaml.load(readFileSync(targetPath, 'utf8')) as Kubeconfig

  it('creates the local kubeconfig readable by the owner only', () => {
    const result = addK8sContext({ sourcePath, targetPath })

    expect(result.contexts).toEqual(['bob-qa@public-k8s-qa-01'])
    expect(result.backupPath).toBeUndefined()
    expect(readTarget()['current-context']).toBe('bob-qa@public-k8s-qa-01')
    if (process.platform !== 'win32') {
      expect(statSync(targetPath).mode & 0o777).toBe(0o600)
    }
  })

  it('backs up the existing kubeconfig before changing it', () => {
    addK8sContext({ sourcePath, targetPath })
    const before = readFileSync(targetPath, 'utf8')
    writeFileSync(
      sourcePath,
      yaml.dump(serverKubeconfig('bob-prod', 'prod-01'))
    )

    const result = addK8sContext({ sourcePath, targetPath })

    expect(readFileSync(result.backupPath!, 'utf8')).toBe(before)
    expect(readTarget().contexts).toHaveLength(2)
  })

  it('leaves the local kubeconfig untouched on a conflict', () => {
    addK8sContext({ sourcePath, targetPath })
    const before = readFileSync(targetPath, 'utf8')

    expect(() => addK8sContext({ sourcePath, targetPath })).toThrowError(
      KubeconfigConflictError
    )
    expect(readFileSync(targetPath, 'utf8')).toBe(before)
    expect(readdirSync(path.dirname(targetPath))).toEqual(['config'])
  })

  it('rejects a file that is not a kubeconfig', () => {
    writeFileSync(sourcePath, 'foo: bar\n')
    expect(() => addK8sContext({ sourcePath, targetPath })).toThrowError(
      /not a valid kubeconfig file: no contexts found/
    )
    expect(existsSync(targetPath)).toBe(false)
  })

  it('rejects a missing file', () => {
    expect(() =>
      addK8sContext({ sourcePath: path.join(dir, 'missing'), targetPath })
    ).toThrowError(/File not found/)
  })

  it('rejects merging the local kubeconfig into itself', () => {
    addK8sContext({ sourcePath, targetPath })
    expect(() =>
      addK8sContext({ sourcePath: targetPath, targetPath })
    ).toThrowError(/already your local kubeconfig/)
  })
})
