interface Window {
  config: {
    API_GATEWAY_URL: string
    BACKGROUND_SYNC_BROADCAST_CHANNEL: string
    COUNTRY: string
    COUNTRY_LOGO_FILE: string
    DESKTOP_TIME_OUT_MILLISECONDS: number
    LANGUAGES: string
    LOGIN_URL: string
    PERFORMANCE_URL: string
    RESOURCES_URL: string
    HEALTH_FACILITY_FILTER: string
    CERTIFICATE_PRINT_CHARGE_FREE_PERIOD: number
    CERTIFICATE_PRINT_CHARGE_UP_LIMIT: number
    CERTIFICATE_PRINT_LOWEST_CHARGE: number
    CERTIFICATE_PRINT_HIGHEST_CHARGE: number
  }
}
