# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Overwriting https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
namespaceOverride: "traefik"
logs:
  general:
    level: "INFO"
    format: "common"
  access:
    enabled: true
ingressRoute:
  dashboard:
    enabled: false

tlsStore: {}

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: false
service:
  enabled: true
  single: false

ports:
  web:
    port: 8000
    protocol: TCP
