# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Clean up environment on PR close

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Show PR info
        run: |
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}"

  on-else:
    runs-on: ubuntu-latest
    steps:
      - name: Show PR info regardless
        run: |
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}"
          echo "PR ${{github.event.pull_request }}"
