# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Reset Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to reset
        required: true
        options:
          - qa
          - config
      replicas:
        description: No of replicas deployed in the environemt
        default: '1'
        required: true
jobs:
  clear:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      REPLICAS: ${{ github.event.inputs.replicas }}
      SSH_HOST: farajaland-${{ github.event.inputs.environment }}.opencrvs.org
      MONGODB_ADMIN_USER: ${{ secrets.MONGODB_ADMIN_USER }}
      MONGODB_ADMIN_PASSWORD: ${{ secrets.MONGODB_ADMIN_PASSWORD }}
      ELASTICSEARCH_ADMIN_USER: elastic
      ELASTICSEARCH_ADMIN_PASSWORD: ${{ secrets.ELASTICSEARCH_SUPERUSER_PASSWORD }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Clear data from given environment
        run: ssh root@$SSH_HOST "MONGODB_ADMIN_USER=$MONGODB_ADMIN_USER MONGODB_ADMIN_PASSWORD=$MONGODB_ADMIN_PASSWORD ELASTICSEARCH_ADMIN_USER=$ELASTICSEARCH_ADMIN_USER ELASTICSEARCH_ADMIN_PASSWORD=$ELASTICSEARCH_ADMIN_PASSWORD /opt/opencrvs/infrastructure/clear-all-data.sh $REPLICAS $ENV"
      - name: Restore backup data in given environment
        run: ssh root@$SSH_HOST "MONGODB_ADMIN_USER=$MONGODB_ADMIN_USER MONGODB_ADMIN_PASSWORD=$MONGODB_ADMIN_PASSWORD /opt/opencrvs/infrastructure/restore-metadata.sh $REPLICAS $ENV"
