# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Test upgrade script

on:
  pull_request:
  workflow_dispatch:
    inputs:
      farajaland-branch:
        description: Farajaland branch name
        default: release-v1.9.13
        required: true

jobs:
  test-upgrade-script:
    runs-on: ubuntu-24.04
    env:
      FARAJALAND_BRANCH: ${{ github.event.inputs.farajaland-branch || 'release-v1.9.13' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn install --frozen-lockfile
      - name: Build toolkit
        run: yarn build:all
        working-directory: packages/toolkit
      - name: Checkout the correct opencrvs-farajaland branch
        run: |
          git clone -b ${{ env.FARAJALAND_BRANCH }} https://github.com/opencrvs/opencrvs-farajaland.git
      - name: Install dependencies
        working-directory: opencrvs-farajaland
        run: yarn install
      - name: Link toolkit
        run: |
          cd packages/toolkit && yarn link
          cd ../../opencrvs-farajaland && yarn link @opencrvs/toolkit
      - name: Run upgrade script
        run: |
          node packages/toolkit/dist/cli.js upgrade opencrvs-farajaland
          # remove some unneeded files
          rm -rf opencrvs-farajaland/src/api/notification/testData.ts
      - name: Test compilation
        run: yarn test:compilation
