# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: Trivy Cache Update
# NOTES: Why this workflow is needed and how it works:
# - https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching#restrictions-for-accessing-a-cache
# Access restrictions provide cache isolation and security by creating a logical boundary between different
# branches or tags. Workflow runs can restore caches created in either the current branch or the default
# branch (usually main). If a workflow run is triggered for a pull request, it can also restore caches created
# in the base branch, including base branches of forked repositories. For example, if the branch feature-b has
# the base branch feature-a, a workflow run triggered on a pull request would have access to caches created in
# the default main branch, the base feature-a branch, and the current feature-b branch.
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-trivy-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy to warm cache
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          exit-code: 0
